### ISSUE TITLE
TF-Serving branch 1.10 doesn't build a working GPU-enabled container for nvidia-docker

### ISSUE THREAD

**Issue by rdwrt** [tensorflow/serving#1031]
The branch 1.10 Dockerfile.devel-gpu doesn't actually compile. 
There are several issues which can be solved with the changes in the sed command below:

Solution: How to compile tf-serving r1.10 successfully for nvidia-docker:
```
wget https://raw.githubusercontent.com/tensorflow/serving/r1.10/tensorflow_serving/tools/docker/Dockerfile.devel-gpu
sed 's/=master/=r1.10/; s/0.11.1/0.15.0/; /stubs/d; ' Dockerfile.devel-gpu > Dockerfile
nvidia-docker build -t tensorflow-serving-r1-10-gpu-devel
```

You might want to use --no-cache during the build if you have issues after previous failed builds.

**Comment by gautamvasudevan** [comment]
Have you tried following the instructions here:
https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/docker.md#building-a-container-from-a-dockerfile

This seems to build for me without issue. Can you follow those instructions and indicate what issues you're running into?

**Comment by rdwrt** [comment]
It breaks because the bazel version given in the Dockerfile is too old.

**Comment by gautamvasudevan** [comment]
https://github.com/tensorflow/serving/blob/r1.10/tensorflow_serving/tools/docker/Dockerfile.devel-gpu
The bazel version is 0.15.0, which is the expected bazel version.

It would be great if you could list your exact steps and exact error message you receive. Otherwise it's difficult to identify your specific issue, given that the dockerfile works locally for me.

**Comment by rdwrt** [comment]
Ok the branch 1.10 still has a wrong bazel version in the Dockerfile, but the tag 1.10.0-rc1 has that part fixed.
Both still have the issue that they use the cuda stubs that stop the models from using the GPU

**Comment by gautamvasudevan** [comment]
Thanks! That is expected and desired so we can build without nvidia-docker. The stubs are not used after building.

**Comment by rdwrt** [comment]
continuing the tutorial on my 1.10 branch build:
```
bazel build --config=cuda -c opt //tensorflow_serving/example:mnist_saved_model
``` 
works, but 
```
bazel-bin/tensorflow_serving/example/mnist_saved_model /tmp/mnist_model
```
crashes, with:
```
tensorflow.python.framework.errors_impl.NotFoundError: /tensorflow-serving/bazel-bin/tensorflow_serving/example/mnist_saved_model.runfiles/org_tensorflow/tensorflow/contrib/rnn/python/ops/_gru_ops.so: undefined symbol: _ZN15stream_executor6Stream12ThenBlasGemmENS_4blas9TransposeES2_yyyfRKNS_12DeviceMemoryIfEEiS6_ifPS4_i
```
This error is same as the one encountered in a tensorflow 1.9 build:
https://github.com/tensorflow/tensorflow/issues/19840

**Comment by gautamvasudevan** [comment]
That mnist example isn't setup to work with GPU acceleration. If you drop the --config=cuda that you added, the example works again.

**Comment by gautamvasudevan** [comment]
FWIW, the mnist model in the Tensorflow Model repo does train and can be served against the GPU.

# Install Tensorflow
cd /
pip install tensorflow
# Create a models directory
mkdir /models
# Clone the TF models repo
git clone https://github.com/tensorflow/models.git
# Setup python for models
export PYTHONPATH="$PYTHONPATH:/models"
# Install requirements
cd /models
pip install --user -r official/requirements.txt
# Train mnist using GPU
cd official/mnist
python mnist.py --export_dir /tmp/mnist_saved_model
# Start model server
tensorflow_model_server --port=8500 --model_name=mnist --model_base_path=/tmp/mnist_saved_model/ &

However, you will need to write a client that queries the model via classification instead of prediction like the one in the TF Serving example. Contributions welcome :)

**Comment by rdwrt** [comment]
Ah thanks! This is helpful set of steps, will see how far I get with this! I just want to go through the process from tf-serving gpu install to functional test with a simple example! Thank you for the pointer!

**Comment by gautamvasudevan** [comment]
Great! I'm going to close this issue given there isn't any obvious bug here. If you have further questions, please post them to [Stack Overflow](https://stackoverflow.com/questions/tagged/tensorflow-serving
) (since it's easier to find questions/answers there).  Thanks!

**Comment by lifeiteng** [comment]
ref https://github.com/tensorflow/tensorflow/issues/19840
```
diff --git a/tensorflow/tensorflow/tf_version_script.lds b/tensorflow/tensorflow/tf_version_script.lds
index 6b28943f01..39d258c3b7 100644
--- a/tensorflow/tensorflow/tf_version_script.lds
+++ b/tensorflow/tensorflow/tf_version_script.lds
@@ -6,6 +6,7 @@ tensorflow {
     *TFE_*;
     *nsync_*;
     *pywrap_xla*;
+    *stream_executor*;
   local:
     *;
 };
```
