### ISSUE TITLE
can I use tensor serving with specified tensorflow?

### ISSUE THREAD

**Issue by fancyerii** [tensorflow/serving#106]
I have built tensorflow 0.8 with gpu. Now I want to try tensor serving. Following the build instruction, it seems tensor serving will clone latest tensorflow source code. is it possible to specify an existed tensorflow installation(I built a whl and install it in virtualenv)?

**Comment by vinuraja** [comment]
Unfortunately, you would have to build the TensorFlow code which comes along with TensorFlow Serving, and cannot reuse an existing installation.

**Comment by Arsakes** [comment]
Is it still the case?

**Comment by chrisolston** [comment]
Yes.

**Comment by Arsakes** [comment]
Current build system makes inclusion of TF serving into linux package systems more difficult.
Would such a change require code edition? Or changing the build configuration would be enough?

**Comment by kirilg** [comment]
The TensorFlow pip package includes all python and some shared libraries needed by the python API. The TensorFlow team could perhaps include additional targets that are needed by TensorFlow Serving, but bazel doesn't yet have support for statically linked libraries, and without it there are C++ ABI issues which would make this problematic. Both of those are efforts underway by the bazel and TF teams, but we're not there yet.

Even if we have such a pip package that we can just link in, I'm not sure if it's the ideal approach here. There are sometimes new changes to TensorFlow that we want to depend on, and that requires us to sync past a certain commit and recompile. In the install-based approach, there will be an (possible cryptic) error at compile time and the user would need to go install a new version of TensorFlow. It'll also make this repo depend on a released pip package and depend on that release cycle. Regardless, if it's simple enough to make it an option to compile from that package, it would be nice.

Once the first two prerequisites land, I'm not yet sure how to make TF Serving work with it, but it should be doable.

**Comment by kirilg** [comment]
Rereading the original question, you wanted to use a manually compiled TensorFlow, not one you installed using pip install. It's a challenging use case to support since older versions will very likely not work with the latest TF Serving because we often depend on new changes to TF that weren't available a while back. You can try updating the path [here](https://github.com/tensorflow/serving/blob/master/WORKSPACE#L5) to point to your TensorFlow repo elsewhere, though I'd be surprised if it just works without a lot of issues. My guess is, even if it does link, bazel will try to recompile everything in that repo because it'll be namespaced in the new TensorFlow serving workspace, and you last compiled standalone TensorFlow. The cleanest approach we have so far is what we have now, including a known-to-work version of TF as a submodule.

**Comment by Arsakes** [comment]
In my distro, TF is always available in latest version since user builds a package out of git sources.
I'm using Archlinux btw. I think in most of rolling release distros one can be pretty sure that packaged version of TF is quite new.
