### ISSUE TITLE
Does tensorflow serving support compiled binary tensorflow model?

### ISSUE THREAD

**Issue by newpoo** [tensorflow/serving#1151]
tfcompile generated AOT model to achieve better inference perf.
If not yet, is it on the tensorflow serving's roadmap?

**Comment by harshini-gadige** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
