### ISSUE TITLE
build tensorflow serving library

### ISSUE THREAD

**Issue by biaochen** [tensorflow/serving#1156]
how to install tf serving as a normal library, so the header files can be found under /usr/local/include and the static libraries can be found under /usr/local/lib? I've tried some workarounds but none seems to work.

**Comment by harshini-gadige** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
