### ISSUE TITLE
Inception model does exists in latest version

### ISSUE THREAD

**Issue by AtulCIS** [tensorflow/serving#1198]
I was trying to create an application with tensorflow serving with inception-v3 model so this model was available since v r1.11 but in latest version I cant find it.
So my question is that why inception-v3 was removed and if its true then what is the alternative now ?

**Comment by gautamvasudevan** [comment]
The Inception example was replaced by a [ResNet example](https://medium.com/tensorflow/serving-ml-quickly-with-tensorflow-serving-and-docker-7df7094aa008) because the Inception example was complicated by its use of checkpoints (which are outside the scope of serving), and which cannot be guaranteed to work across TF versions (making it a fragile example).

These are only examples, you can serve whatever SavedModel you like (including an [Inception model](https://github.com/tensorflow/models/tree/master/research/inception)) using TensorFlow Serving.

**Comment by gautamvasudevan** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it's not a serving issue any longer, but a question about how the model works and how to convert the data into something you'd like to use. There is also a larger community that reads questions there. Thanks!

**Comment by AtulCIS** [comment]
Yes I understand but the response is coming from the api so I think you are well aware with this as compared to stackoverflow ?
For eg. in case of Inception this is the output https://i.imgur.com/CuSmaNc.jpg but in case of resnet client and resnet grpc output is different https://i.imgur.com/aNMZTMl.jpg and https://i.imgur.com/h5zME5K.jpg.
So I can do search on stackoverflow if  I need any technical help but in my case I want to know about the output pattern and how this model is supposed to give response ?

**Comment by gautamvasudevan** [comment]
Unfortunately providing support for specific models is beyond the scope of this project. You’ll have better luck getting experts to help you on StackOverflow.

Thanks!
