### ISSUE TITLE
Problem while following the inception inference problem, woch docker

### ISSUE THREAD

**Issue by mch5048** [tensorflow/serving#129]
I'm following the Tensorflow Serving tutorial of the "Serving Inception Model Tutorial". I succeeded all the previous command steps as intstructed. However, I'm stuck on the below command,
It logs  "IOError: [Errno 2] No such file or directory: '/path/to/my_cat_image.jpg'"..
I can't assume any possible solution for this..
What could be the cause of this problem ?????
-------------------------------------------------------------------------------------------------------------------------------
root@345a912685b9:/serving# bazel-bin/tensorflow_serving/example/inception_client --server=localhost:9000 --image=/path/to/my_cat_image.jpg
D0719 19:16:32.526302381      37 ev_posix.c:101]             Using polling engine: poll
Traceback (most recent call last):
  File "/serving/bazel-bin/tensorflow_serving/example/inception_client.runfiles/tensorflow_serving/example/inception_client.py", line 56, in <module>
    tf.app.run()
  File "/serving/bazel-bin/tensorflow_serving/example/inception_client.runfiles/external/org_tensorflow/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "/serving/bazel-bin/tensorflow_serving/example/inception_client.runfiles/tensorflow_serving/example/inception_client.py", line 46, in main
    with open(FLAGS.image, 'rb') as f:
IOError: [Errno 2] No such file or directory: '/path/to/my_cat_image.jpg'

------------------------------------------------------------------------------------------------------------------------------

**Comment by apodolny** [comment]
You need to replace 'path/to/my_cat_image.jpg' with a filepath for an actual image that you'd like inception to categorize.

**Comment by mch5048** [comment]
@apodolny Thanks for your reply!  I changed the path with '/home/myname/Pictures/abcd.jpg, but the logs says the same result..... how can I set the path for the image? I saved it in my system.

**Comment by sukritiramesh** [comment]
Hi @mch5048, are you seeing this issue specifically with Docker? If so, you could try to use the docker run command with the -v option to be able to use the image with the container: https://docs.docker.com/engine/reference/commandline/run/

**Comment by kirilg** [comment]
If you're following the [instructions here](https://tensorflow.github.io/serving/serving_inception) and are running the server and client inside a Docker container, note that a container is isolated from the rest of your system, so you have two options when specifying the file:
1) As Sukriti mentioned, use the -v option to mount a local directory when starting up a Docker container so that it can see that directory (otherwise directories on your machine outside the container are not visible inside the container).
2) Download a picture directly within your container so that it appears there (e.g. just like the `curl -O http://download.tensorflow.org/models/image/imagenet/inception-v3-2016-03-01.tar.gz` command is run within the container).

If the file is visible within the container, the client command should work. i.e. if you can run
`root@c97d8e820ced:/# ls home/myname/Pictures/abcd.jpg`
