### ISSUE TITLE
When will TFS support TF 2.0?

### ISSUE THREAD

**Issue by ericwang915** [tensorflow/serving#1294]
TF 2.0 has introduced some very cool features such as tf.function and autograph. When will TFS support the serialised model using TF 2.0.

**Comment by unclepeddy** [comment]
TFS will have a 2.0 release following TF 2.0's official release (no exact date yet unfortunately). 

However, most of the new features in 2.0 should not have an impact on serving since they will result in a SavedModel with the same semantics as 1.X (SavedModel in 2.0 is very similar to SavedModel in 1.X). 

If you export 2.0 models that don't work with TFS, please do file an issue so that we can track known problematic models leading up to TFS 2.0.

Thanks!

**Comment by hgadig** [comment]
Closed the issue as this has been answered above.
