### ISSUE TITLE
bazel build error(gcc: internal compiler error: Killed) for tensorflow_serving/example:mnist_inference

### ISSUE THREAD

**Issue by fredwang222** [tensorflow/serving#13]
Hi there,

   I got error when build example. My gcc is gcc (Ubuntu 4.8.4-2ubuntu1~14.04.1) 4.8.4,  and 
Here is the error information. Do u have a docker version for serving? Thanks!
(cd /home/xxxx/.cache/bazel/_bazel_xxxx/85b1cab135cf9be23a6843da5c416dee/serving && \
  exec env - \
    PATH=/home/xxxx/tensorflow2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/bin/libsvm/:/usr/bin/liblinear:/home/xxxx/bin \
  /usr/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -iquote external/tf -iquote bazel-out/local_linux-fastbuild/genfiles/external/tf -iquote external/bazel_tools -iquote bazel-out/local_linux-fastbuild/genfiles/external/bazel_tools -iquote external/jpeg_archive -iquote bazel-out/local_linux-fastbuild/genfiles/external/jpeg_archive -iquote external/png_archive -iquote bazel-out/local_linux-fastbuild/genfiles/external/png_archive -iquote external/re2 -iquote bazel-out/local_linux-fastbuild/genfiles/external/re2 -iquote external/eigen_archive -iquote bazel-out/local_linux-fastbuild/genfiles/external/eigen_archive -isystem external/tf/google/protobuf/src -isystem bazel-out/local_linux-fastbuild/genfiles/external/tf/google/protobuf/src -isystem external/bazel_tools/tools/cpp/gcc3 -isystem external/jpeg_archive/jpeg-9a -isystem bazel-out/local_linux-fastbuild/genfiles/external/jpeg_archive/jpeg-9a -isystem external/png_archive/libpng-1.2.53 -isystem bazel-out/local_linux-fastbuild/genfiles/external/png_archive/libpng-1.2.53 -isystem external/re2 -isystem bazel-out/local_linux-fastbuild/genfiles/external/re2 -isystem external/tf/third_party/eigen3 -isystem bazel-out/local_linux-fastbuild/genfiles/external/tf/third_party/eigen3 -isystem external/eigen_archive/eigen-eigen-ed4c9730b545 -isystem bazel-out/local_linux-fastbuild/genfiles/external/eigen_archive/eigen-eigen-ed4c9730b545 -fno-exceptions -DEIGEN_AVOID_STL_ARRAY -pthread -no-canonical-prefixes -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' '-frandom-seed=bazel-out/local_linux-fastbuild/bin/external/tf/tensorflow/core/kernels/_objs/cwise_op/external/tf/tensorflow/core/kernels/cwise_op_not_equal_to.pic.o' -MD -MF bazel-out/local_linux-fastbuild/bin/external/tf/tensorflow/core/kernels/_objs/cwise_op/external/tf/tensorflow/core/kernels/cwise_op_not_equal_to.pic.d -fPIC -c external/tf/tensorflow/core/kernels/cwise_op_not_equal_to.cc -o bazel-out/local_linux-fastbuild/bin/external/tf/tensorflow/core/kernels/_objs/cwise_op/external/tf/tensorflow/core/kernels/cwise_op_not_equal_to.pic.o).
gcc: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
Target //tensorflow_serving/example:mnist_inference failed to build

**Comment by kirilg** [comment]
The version of gcc is fine. This is a gcc internal error and I don't see anything Tensorflow specific, not sure exactly what the problem is. Some initial search lead to several threads that said it's because gcc doesn't have enough memory, so you can try following some of their advice to see if it'll help (e.g. https://bitcointalk.org/index.php?topic=304389.0).

I couldn't reproduce locally, and trying to simulate low memory, I ran
bazel build --local_resources 256,2.0,1.0 tensorflow_serving/example:mnist_inference
// uses 256M of ram, but that still compiled successfully.

As for your other question, we do have a docker setup (http://tensorflow.github.io/serving/docker). The dockerfile is here (https://github.com/tensorflow/serving/blob/master/tensorflow_serving/tools/docker/Dockerfile.devel). It sets up the environment, but doesn't have precompiled Tensorflow serving, you'd still need to git clone and compile yourself.
Might be worth compiling in this docker container to eliminate the possibility that it's some environment issue.

**Comment by fredwang222** [comment]
Thanks! I tried  --local_resources 256,2.0,1.0 and another issue occur 'ERROR: /home/xxx/tensorflow2/serving/tensorflow_serving/session_bundle/e     xample/BUILD:34:1: Executing genrule //tensorflow_serving/session_bundle/ex     ample:half_plus_two failed: bash failed: error executing command /bin/bash      -c ... (remaining 1 argument(s) skipped).
2546 RuntimeError: module compiled against API version a but this version of num     py is 9' but let me close this one temporarily and reopen it if it occurs again!
