### ISSUE TITLE
official release linked with sentencepiece

### ISSUE THREAD

**Issue by taylorchu** [tensorflow/serving#1333]
## Feature Request
If this is a feature request, please fill out the following form in full:

### Describe the problem the feature is intended to solve

I will have to link sentencepiece with serving myself. Ideally, I want to use the docker image with serving linked with sentencepiece.

### Describe the solution

official release linked with sentencepiece.

### Describe alternatives you've considered
A clear and concise description of any alternative solutions or features you've
considered.

**Comment by lilao** [comment]
Hi,

Because there are a large number of ops, it's infeasible to maintain ModelServer docker builds with all the possible ops. Can you build your own ModelServer binary and link in the ops that you need? Here are the instructions on how to build from source: https://github.com/tensorflow/serving#set-up. Please let us know if you have other questions.

**Comment by taylorchu** [comment]
@lilao 
1. sentencepiece is used in [xling](https://tfhub.dev/google/universal-sentence-encoder-xling-many/1) tensorflow hub module, and people expect it to work with tensorflow ecosystem.
2. There was a task to add it to tf.contrib but it was abandoned because tf 2.0 will remove tf.contrib. There is no other subword tokenization ops for tensorflow.

**Comment by gowthamkpr** [comment]
@martinwicke @lilao Can we please take a look at this request. Thanks!

**Comment by martinwicke** [comment]
The serving team is working on enabling dynamic loading of op libraries, but I think it'll take a while longer.
