### ISSUE TITLE
How could I get the transmission time？

### ISSUE THREAD

**Issue by ginger0106** [tensorflow/serving#1349]
I am using the TFS Docker, I could only got the end-to-end latency by measuring the send request time and response time. How could I get the network transmission time and inference time respectively? Thanks

**Comment by gowtham-kp** [comment]
This question is better asked on [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow-serving) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/serving/issues/new). Thanks!

**Comment by lxl910915** [comment]
@ginger0106 Have you find the way to get the transmission time? Thanks.
