### ISSUE TITLE
when will serving support tensorflow2.0?

### ISSUE THREAD

**Issue by topxxuki** [tensorflow/serving#1398]

**Comment by rmothukuru** [comment]
@topxxuki ,
Can you please elaborate your question. 

Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by topxxuki** [comment]
![image](https://user-images.githubusercontent.com/18697846/61875643-ad6c9e80-af1d-11e9-950f-af5734e8159e.png)
nowadays we can use tensorflow_v2.0,but serving only support 0.14,when will serving support 2.0?

**Comment by rmothukuru** [comment]
@topxxuki ,
Can you please specify your use case for which you require TF Serving 2.0 so that we can try to help you out.

**Comment by topxxuki** [comment]
> @topxxuki ,
> Can you please specify your use case for which you require TF Serving 2.0 so that we can try to help you out.

there is not a  particular scene，i thought each tensorflow version will have  corresponded serving

**Comment by unclepeddy** [comment]
Thanks @topxxuki you are correct that we try to be on the same schedule as TF. However, we only start our release process for a given TF version once they cut the branch - the ones you are mentioning are the alpha and beta previews, not an official 2.0 branch (though that should be happening in the next week I believe). Once it does, we will kick off our release and cut tf serving 2.0 :)
