### ISSUE TITLE
how to write a tensorflow serving platform_config_file for customized servable?

### ISSUE THREAD

**Issue by tilaba** [tensorflow/serving#1422]
we have created a customized servable according to the reference [https://www.tensorflow.org/tfx/serving/custom_servable](url) .  I want to run my servable by virtue of a  platform_config_file and model_config_file. how can I write a serving platform_config_file for customized serverable such as  pytorch_souce_adapter.

**Comment by rmothukuru** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by tilaba** [comment]
for example, i want to serve a pytorch model, the servable part has been finished. I dont know how to write the platform config file.  the following is demo of torch_bundle_source_adapter.  i dont know whether it is ture, please help me. 

# platform_configs {
#    key: "pytorch"
#     value {
#       source_adapter_config {
#        [TorchSourceAdapterConfig] {
#           config {
#             force_cpu_only : true
#           }
#         }
#       }
#     }
# }

**Comment by vinuraja** [comment]
Source_adapter_config is an Any proto. So it should be something like:
```code
platform_configs {
  key: "pytorch"
  value {
    source_adapter_config {
      [type.googleapis.com/full.type.name.Message] {
          // Message filled up.
      }
    }
  }
}
```
