### ISSUE TITLE
Built TF model server outside of image 

### ISSUE THREAD

**Issue by amrithadevadiga** [tensorflow/serving#1428]
Hi all,

I want Built TF model server 1.10 outside of image and moved it through Dockerfile 

can some one give me steps to do that in centos7

**Comment by rmothukuru** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by amrithadevadiga** [comment]
@rmothukuru  ,

Hi , i am looking to build TF Serving version 1.10.0 (TF model server) on centos7 image in need steps for it. after that i have plan of inserting in dockerfile to build another image which my one of different requirement.

**Comment by rmothukuru** [comment]
@amrithadevadiga ,
Can you please confirm if this is tracked in #1424.

**Comment by amrithadevadiga** [comment]
yes.
