### ISSUE TITLE
Tips for newbie trying to export a model

### ISSUE THREAD

**Issue by jspauld** [tensorflow/serving#143]
I can follow the instructions to export a model here: https://tensorflow.github.io/serving/serving_basic

But how do I make this work for my own model? I don't have this bazel stuff setup in my own repository. The following does not work:

```
$>bazel build //tensorflow_serving/example:mnist_export
$>bazel-bin/tensorflow_serving/example/mnist_export /tmp/mnist_model
Training model...
```

Do I need to create the following files for my own model?

https://github.com/tensorflow/serving/blob/master/tensorflow_serving/example/BUILD
https://github.com/tensorflow/serving/blob/master/tensorflow_serving/BUILD
https://github.com/tensorflow/serving/blob/master/tensorflow_serving/serving.bzl
https://github.com/tensorflow/serving/blob/master/tensorflow_serving/workspace.bzl

If so, how? Why is there so much code in these files?

Is there an example somewhere that shows the minimal number of steps required to export a basic TensorFlow model from scratch? Forget MNIST -- just have it return a+b.

I've been able to setup Docker to run a server and I think I know how to use gRPC to connect my client application. Exporting my model seems to be incredibly difficult.

**Comment by kirilg** [comment]
This can be a bit confusing when first getting started with Bazel, but let me explain what those files do. I'd also recommend going through some high level [Bazel documentation](http://www.bazel.io/docs/getting-started.html) to get the general idea behind workspace and build files.

You won't need to create all of the files you mentioned, but if you'll be using Bazel in your repo, you'll need one WORKSPACE file for the whole repo and a BUILD file in each directory. BUILD files specify build targets to compile, so their size often correlates with the number of source files in that directory.

`serving.bzl` contains skylark macros that can be used in build files. Right now it just has functions to help define cc and python protos, which you likely won't need. Even if you do, you can just load(..) that file instead of creating your own.

`workspace.bzl` contains one macro for setting up the workspace with all external dependencies. It's only used from within the WORKSPACE file, and if you use Bazel you'll likely want to use it in your WORKSPACE file as well.

NOTE: Since the whole session_bundle directory was recently moved to the main Tensorflow repo under contrib, you should be able to pip install Tensorflow and just use the python modules like `exporter.py` without using Bazel at all, the way you'd use any other TF python libraries. However, you may have to wait for the next release since I'm not sure the latest has all of those changes.

---

For a simpler example like a+b, see [half_plus_two](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/session_bundle/example/export_half_plus_two.py). The model is just y=0.5x+2 where x is the input and y is the output. That directory has just one file and one BUILD file. The BUILD file has some boilerplate details that we use (package visibility, license) but the only relevant rule for you is `export_half_plus_two` which is a python binary rule.

**Comment by jspauld** [comment]
Thanks! I must have been using an older version of TF because the exporter is now working without  Bazel. Much simpler -- would be nice to update the [documentation](https://tensorflow.github.io/serving/serving_basic.html).

It turns out TF serving may not be what I need. My goal is to run inference from a C# application as fast as possible. Perhaps a DLL will be simpler and cut out some overhead processing?

Reading [this post](https://medium.com/jim-fleming/loading-a-tensorflow-graph-with-the-c-api-4caaff88463f#.gue31l6c0) and [this post](https://medium.com/@hamedmp/exporting-trained-tensorflow-models-to-c-the-right-way-cf24b609d183#.oomiagde9) I was able to get my model running as an executable using the C++ API and Bazel. Now I'm trying to figure out how to build a DLL from Bazel so I can use it in my application. Can Bazel do that? And if not is it possible to build a DLL in Visual Studio that will run inference on a TF model?

**Comment by kirilg** [comment]
Sounds like you got things working before, sorry for the long delay in responding.

We've since moved the exporter to use the new SavedModel format and all documentation has been updated.

I'm not sure about your DLL question, I've never tried it myself. Not sure if it's still relevant, and the original question was more about exporting, so I'll close this issue but feel free to open a new one about building a DLL and maybe someone from the community has some experience with it.

**Comment by fastlater** [comment]
@jspauld @kirilg  Did you find a more direct way to import the model to C#? I tried with emguTF but if the model is complex, I get error.
I was asking to cntk but I am not sure if they will release a tool soon or not.
I am also a c# programmer and I would like to make my model run in c# so I can incorporate it to my projects.

**Comment by kirilg** [comment]
Perhaps your best bet would be to use the standard ModelServer (C++) and write your own C# client to query it. See https://grpc.io/docs/quickstart/csharp.html. I have no experience with using grpc in C# but maybe you can give it a try.

I don't know of a way to load the model directly in C# if you don't want to run a separate server, all of our libraries are in C++.
