### ISSUE TITLE
No "model" directory inside image - tensorflow/serving:latest-devel-gpu 

### ISSUE THREAD

**Issue by ashwini-git** [tensorflow/serving#1433]
Hi ,

I am trying to use **"TensorFlow/serving:latest-devel-gpu"** image. while I was trying to copy my model into the container**/models** it throws error **models/ directory is not available in the container image.** 

following are the directories i see - 
`docker exec -t -i 5e22abf46359 /bin/bash`
> BUILD,batching, core,g3doc, repo.bzl, servables    , sources, tools  
  , workspace.bzl
> apis,config, example    ,model_servers    ,resources , serving.bzl    ,test_util   , util

whereas the image " TensorFlow/serving:latest-gpu" has "model" directory in it 

> bin  , boot  ,dev , etc  ,home , lib,  lib64,  media,  mnt,  **models,**  opt,  proc,  root , run , sbin,  srv,  sys , tmp , usr,  var

 Help me to understand , why there is no model directory into the image -**tensorflow/serving:latest-devel-gpu** ? Since the "models" directory is not available , where should I copy my models to be able to serve it.

**Comment by rmothukuru** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow Serving version.

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by wdirons** [comment]
The `devel` containers only exist so that you can compile TensorFlow Serving using bazel inside of the container. (For testing changes to the TensorFlow serving code.) They don't contain the tensorflow_model_server binary or the /models directory, so they can not be used to run tensorflow serving. Only for compiling it.

For more info see: https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/building_with_docker.md

**Comment by rmothukuru** [comment]
@ashwini-git ,
Can you please confirm if @wdirons's comments helped you.

**Comment by ashwini-git** [comment]
@wdirons Thank You! Closing the issue.
