### ISSUE TITLE
Tensorflow Serving or froze inference graph

### ISSUE THREAD

**Issue by PythonImageDeveloper** [tensorflow/serving#1493]
Hi everyone,
I have some question, if possible please help me.
I've trained the Tensorflow model, and I want to use the trained model in two scenario of production:
We have two solution : one is handle by **froze inference graph (.pb file)** and another is handle by  **Tensorflow Serving API**.

1-  **web service scenario:** In my opinion, the best solution is handling by Tensorflow Serving API, Because this API easily handling Multi-Threading and Multi-Processing problems, right?

2 - **local processing scenario like jetson nano:** In my opinion, handling by froze inference graph (.pb file) can be good solution, right? but I don't know the Tensorflow Serving API can be handling this scenario?

I'm looking forward to your ideas and solutions.

Thanks.

**Comment by gowthamkpr** [comment]
`1- web service scenario: In my opinion, the best solution is handling by Tensorflow Serving API, Because this API easily handling Multi-Threading and Multi-Processing problems, right?`

Yes, TF Serving handles [Multi-Threading](https://stackoverflow.com/questions/47825958/does-tensorflow-serving-supports-multi-threading) and [Multi-Processing](https://hackernoon.com/how-we-improved-tensorflow-serving-performance-by-over-70-f21b5dad2d98). 

`2 - local processing scenario like jetson nano: In my opinion, handling by froze inference graph (.pb file) can be good solution, right? but I don't know the Tensorflow Serving API can be handling this scenario?`

Yes, you are right. TF serving only uses saved model and doesn't use frozen graph to serve the model. So, I would recommend not using TF serving in this case.

**Comment by PythonImageDeveloper** [comment]
Thanks.
Are the TF-Serving and TFX the same API and concept? In the website tensorflow I only see TFX keyword, are these the same?

**Comment by gowthamkpr** [comment]
They are not. Please take a look [here](https://github.com/tensorflow/tfx)

**Comment by gowthamkpr** [comment]
Closing this issue as it has been answered. Please post support related questions on stackoverflow. Thanks!
