### ISSUE TITLE
Chain multiple estimators to create a single SavedModel

### ISSUE THREAD

**Issue by tejaslodaya** [tensorflow/serving#1523]
Chain multiple estimators to create a single SavedModel with a single serving file/output.

Suppose I have 3 estimators with me, first is BoostedTrees, who's output I want to use as input into DNNClassifier, and the output of which I want to use in my custom Estimator.

Is there a way to chain output/input of each other to create a *mega* estimator of sorts.

Please help me out here.

**Comment by tejaslodaya** [comment]
TF version - 2.0
Using Estimators, not sessions/graphs.

CC: @ymodak @unclepeddy

**Comment by tejaslodaya** [comment]
Hi @lilao @rmothukuru ,

Any update on the above would be appreciated.

**Comment by gowthamkpr** [comment]
@tejaslodaya In order to serve an estimator model with tensorflow serving, we must export the trained model with export_savedmodel method. The method requires serving_input_receriver_fn. All these methods are related to tensorflow and not serving as shown [here](https://www.tensorflow.org/api_docs/python/tf/estimator/export/ServingInputReceiver?version=stable). So, please post this question on tensorflow/tensorflow. Thanks!

**Comment by tejaslodaya** [comment]
But is there a way to combine more than one estimator's output into a single endpoint?
Suppose I have 3 different estimators, and using the above code will give me 3 different endpoints.

I want to combine outputs of different estimators and serve it using one single endpoint.

This surely comes under the bucket of tf-serving CC: @gowthamkpr

**Comment by gowthamkpr** [comment]
@tejaslodaya I am sorry. I get it now.

This feature has not been implemented in Tensorflow Serving. My recommendation would be to run these 3 models individually using Tensorflow serving at the same time and combine these requests at the client side.

**Comment by unclepeddy** [comment]
Just a +1 that this should be doable in TF - if you're having difficulty chaining estimators, please do ask on StackOverflow or TF community, but this is very much outside the scope of TF Serving.
