### ISSUE TITLE
build failed on Centos 6.7 with Error: no such instruction: `vbroadcasti128 .Lsigma(%rip),%ymm11'

### ISSUE THREAD

**Issue by striveth** [tensorflow/serving#1531]
Command:
bazel build -c opt //tensorflow:libtensorflow_cc.so
Message:
ERROR: /home/xiaoju/.cache/bazel/_bazel_xiaoju/be98a53b27ec7c052c1f167e0f93692d/external/boringssl/BUILD:130:1: C++ compilation of rule '@boringssl//:crypto' failed (Exit 1)^M
external/boringssl/linux-x86_64/crypto/cipher_extra/chacha20_poly1305_x86_64.S: Assembler messages:
external/boringssl/linux-x86_64/crypto/cipher_extra/chacha20_poly1305_x86_64.S:4104: Error: no such instruction: `vbroadcasti128 0(%r9),%ymm4'
external/boringssl/linux-x86_64/crypto/cipher_extra/chacha20_poly1305_x86_64.S:4105: Error: no such instruction: `vbroadcasti128 16(%r9),%ymm8'
external/boringssl/linux-x86_64/crypto/cipher_extra/chacha20_poly1305_x86_64.S:4106: Error: no such instruction: `vbroadcasti128 32(%r9),%ymm12'
external/boringssl/linux-x86_64/crypto/cipher_extra/chacha20_poly1305_x86_64.S:4107: Error: suffix or operands invalid for `vpaddd'
external/boringssl/linux-x86_64/crypto/cipher_extra/chacha20_poly1305_x86_64.S:4118: Error: suffix or operands invalid for `vpaddd'
external/boringssl/linux-x86_64/crypto/cipher_extra/chacha20_poly1305_x86_64.S:4119: Error: suffix or operands invalid for `vpxor'
external/boringssl/linux-x86_64/crypto/cipher_extra/chacha20_poly1305_x86_64.S:4120: Error: suffix or operands invalid for `vpshufb'
external/boringssl/linux-x86_64/crypto/cipher_extra/chacha20_poly1305_x86_64.S:4121: Error: suffix or operands invalid for `vpaddd'
external/boringssl/linux-x86_64/crypto/cipher_extra/chacha20_poly1305_x86_64.S:4122: Error: suffix or operands invalid for `vpxor'
external/boringssl/linux-x86_64/crypto/cipher_extra/chacha20_poly1305_x86_64.S:4123: Error: suffix or operands invalid for `vpsrld'
external/boringssl/linux-x86_64/crypto/cipher_extra/chacha20_poly1305_x86_64.S:4124: Error: suffix or operands invalid for `vpslld'
external/boringssl/linux-x86_64/crypto/cipher_extra/chacha20_poly1305_x86_64.S:4125: Error: suffix or operands invalid for `vpxor'
external/boringssl/linux-x86_64/crypto/cipher_extra/chacha20_poly1305_x86_64.S:4126: Error: suffix or operands invalid for `vpaddd'
external/boringssl/linux-x86_64/crypto/cipher_extra/chacha20_poly1305_x86_64.S:4127: Error: suffix or operands invalid for `vpxor'
external/boringssl/linux-x86_64/crypto/cipher_extra/chacha20_poly1305_x86_64.S:4128: Error: suffix or operands invalid for `vpshufb'
external/boringssl/linux-x86_64/crypto/cipher_extra/chacha20_poly1305_x86_64.S:4129: Error: suffix or operands invalid for `vpaddd'
external/boringssl/linux-x86_64/crypto/cipher_extra/chacha20_poly1305_x86_64.S:4130: Error: suffix or operands invalid for `vpxor'
external/boringssl/linux-x86_64/crypto/cipher_extra/chacha20_poly1305_x86_64.S:4131: Error: suffix or operands invalid for `vpslld'
external/boringssl/linux-x86_64/crypto/cipher_extra/chacha20_poly1305_x86_64.S:4132: Error: suffix or operands invalid for `vpsrld'

tensorflow version 1.12.0
bazel version 0.15.0
CentOS release 6.7 (Final)
gcc version 4.8.2 (GCC)
GNU ld (GNU Binutils) 2.31
Python 2.7.9

How to solve it ? Thx

**Comment by rmothukuru** [comment]
@striveth,
Can you please confirm if you are trying to install Tensorflow or Tensorflow Serving. If you want to install Tensorflow and are facing issues, please raise an Issue in this [Tensorflow Repository](https://github.com/tensorflow/tensorflow/issues). 

If you are trying to install Tensorflow Serving, can you please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by striveth** [comment]
Sorry, build tensorflow.
