### ISSUE TITLE
gRPC API: HandleReloadConfigRequest() return Deadline Exceeded 2

### ISSUE THREAD

**Issue by namjals** [tensorflow/serving#1565]
Is the same as the following issue, but since it is closed, registered again.
https://github.com/tensorflow/serving/issues/1447

This problem is reproduced. The code is shown below. I need help.
# docker run script
docker run -t --rm -d \
-p 8501:8501 \
-p 8500:8500 \
-v "{model_path}:/models/" --name serving tensorflow/serving --model_config_file={config_path} --model_config_file_poll_wait_seconds=10

# config file
model_config_list: {
   config: {
    name:  "model",
    base_path:  "{not exsist path}",
    model_platform: "tensorflow",
  }
}

# tensorflow serving error log
FileSystemStoragePathSource encountered a filesystem access error: Could not find base path {not exist path} for servable model

# python, reload script by grpc
hostport = 'localhost:8500'
path = {config_path}
with open(path, "r") as f:
    config_ini = f.read()
model_server_config = model_server_config_pb2.ModelServerConfig()
model_server_config = text_format.Parse(text=config_ini, message=model_server_config)
channel = grpc.insecure_channel(hostport)
stub = model_service_pb2_grpc.ModelServiceStub(channel)
request = model_management_pb2.ReloadConfigRequest()
request.config.CopyFrom(model_server_config)
response = stub.HandleReloadConfigRequest(request, 10)
if response.status.error_code == 0:
    print("Reload done") 

Modifying the config file will not be reflected because the serving does not poll the config file.

**Comment by namjals** [comment]
I want to use tensorflow serving as a real-time server.
But when I incorrectly edit the config file, the server gets stuck. Then I have no choice but to restart the server. 

I have two questions.
1. Ask if there is a way to restore the server to poll the config file again.
2. In addition, if the server is stuck, there is a way to check the server's status with restapi or script.

**Comment by gowthamkpr** [comment]
Can you please answer this [question](https://github.com/tensorflow/serving/issues/1447#issuecomment-540237563) in detail @namjals . Thanks!

**Comment by namjals** [comment]
1) What you're doing
Deploy the model in real time. The config file changes in real time.

2) What the observed outcome is and
When the server polls the config file every 10 seconds and sets model_config_list ['config'] ['base_path'] in the config file to the wrong path, the service outputs an error log.
At this point, the serving no longer polls the config file.

3) What the expected outcome is?
Expect to keep polling the config file even if the serving error occurs.
Because when a serving error occurs, I want to restore the config file by modifying it. I do not want to restart the serving.

Also, even if the serving error occurs, when using the gRPC API: HandleReloadConfigRequest (), it expects to reload the requested config instead of "Deadline Exceeded".

What I most expect is that if the model_config_list ['config'] ['base_path'] goes wrong, the serving behavior should be fine. When requesting model prediction for incorrect settings, expect to return an error from the serving.

Or if a restapi is provided that checks the status of the TensorFlow serving, it would be nice to return the list that is being served normally and the list that is not being served due to an error.

**Comment by gowthamkpr** [comment]
@misterpeddy Can you PTAL? Thanks!

**Comment by misterpeddy** [comment]
Yes this is not ideal from a UX standpoint but it's somewhat difficult to fix from a technical perspective, which I'll try to explain below. 

/cc @christisg and @netfs to keep me honest.

When the server starts up, it'll read the config file and try to serve what has been asked. It does not finish the process of construction of the server (ServerCore, an internal interface, to be exact) until it's been able to load what is prescribed in the config. 

The periodic polling for model config file happens **after** the ServerCore object has been created [1] because otherwise, there is a potential for the polling thread and the main thread (executing ServerCore::Create) to concurrently try to set the config.. which could cause undesirable race conditions..

The way around this is to ensure that you *start* TF Serving with a valid config. After startup, it should be fine if the config has invalid entries, but the config file polling mechanism is only kicked off after serving a model successfully, so just ensure that the original config is valid and you'll be fine.

Again, I agree the behavior is undesirable but the workaround is "provide a valid config at startup." I'm gonna close this - feel free to lmk if I've misunderstood your problem.

[1] https://github.com/tensorflow/serving/blob/master/tensorflow_serving/model_servers/server.cc#L289

**Comment by namjals** [comment]
@misterpeddy
I think my problem is well communicated. But there is one strange part.
As you say, when I start the server with a valid config, there is no problem. After modifying the existing settings to invalid ones, I confirmed that the server did not stop polling the config file.
However, after adding the wrong setting to the existing setting, it stops polling.
```
model_config_list {
  config {
    // valid config.
  }
}
-> fine.

model_config_list {
  config {
    // updated invalid config. (invalid base_path)
  }
}
-> fine. still polling config file.

model_config_list {
  config {
    // invalid config. (invalid base_path)
  }
  config {
    // added valid config.
  }
}
-> don't polling config file.
```
Probably, the modified config does not created a ServerCore object even with an invalid setting.
However, adding config in this state seems to be trying to create a ServerCore object.
The test version is `docker pull tensorflow / serving: latest`.
I think I should update the config file after verification.
Thank you.

**Comment by yzhaoa** [comment]
@namjals based on reading of the codebase (as of Jan 2024) and testing, I've found two causes that can cause HandleReloadConfigRequest() to block indefinitely:

1. Not initializing the server at startup. If the server is started with an empty configuration, as mentioned up thread, it does not fully initialize its internal states. Under this condition, when a new model is loaded HandleReloadConfigRequest(), but fails to load for any reason, the server would enter an inconsistent state - it tracks the failed-to-load model as Aspired, but does not store that config in memory. This can lead to a deadlock under the following situation:
    1. You try to load model A, it fails
    2. You try to load model B, it successfully loads. This initializes the server in an inconsistent state - the AspiredVersionsManager tracks model A as failed, but storage_path_source_and_router_ does not track model A.
    3. You try to load model A again, the reload process deadlocks. This is because the logic in reload attempts to wait for model A to startup, but the model has already failed, so it never receives any events for model A. This was tested under max_num_load_retries=0.
2. The model you're trying to load has an invalid directory layout. In particular, if the the model base_path does not contain any integer directories (e.g. model/1/), or does not exist at all, FileSystemStoragePathSource never attempts to report anything about the model to AspiredVersionsManager. Because AspiredVersionsManager is ultimately responsible for reporting the model state, either successful or failed, this means that your new failed model with an invalid base_path never gets reported, and thus ReloadConfig blocks forever.

Thus, to avoid the deadline exceeded situation, you should:

1. Start the server with an empty config containing `model_config_list {}`. Note it doesn't actually have to have any models, just that the server must be initialized under model_config_list mode (as opposed to custom_model_config mode).
2. When attempting to load new models, make absolutely sure that any models' base_path that you send via HandleReloadConfigRequest:
    1. Exists
    2. Contains integer directories
    3. If specific versions are selected in the ModelConfigs, you must also make sure that at least one of those specific versions exist as a directory.

With the above setup, I was able to issue any number of HandleReloadConfigRequest to the server without it breaking.
