### ISSUE TITLE
Documentation of how to deploy parsey's cousins model with tensorflow serving?

### ISSUE THREAD

**Issue by johann-petrak** [tensorflow/serving#164]
Is there some documentation about how to do this?

**Comment by kirilg** [comment]
We don't have documentation specific to parsey's cousins, just general [exporter documentation](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/session_bundle/README.md) that shows how to export a model compatible with TensorFlow Serving and other examples that do it for similar models.

For example, [this](https://github.com/tensorflow/models/blob/master/inception/inception) is the inception model in Tensorflow/models, and [this](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/example/inception_export.py) is an example in our repo that can load a training checkpoint saved by inception and export that graph in a format that TensorFlow serving can load. [This](https://tensorflow.github.io/serving/serving_inception) is the documentation for running this tutorial. Note that the `curl -O http://download.tensorflow.org/models/image/imagenet/inception-v3-2016-03-01.tar.gz` command gets the trained inception checkpoint which will be very similar (in format) to the checkpoint you'll get from parsey's cousins. Then inception_export loads the checkpoint and exports a version.

This seems cumbersome, but normally it's easier than that when you write your own model and train it yourself, such that adding the exporter is minimal overhead. Ideally all of these examples would provide models directly loadable by TF Serving, but unfortunately for now they're just exposing checkpoints since most users just want to load it in TF and not use for production serving.
