### ISSUE TITLE
How to ensure the thread synchronization of grpc server, HTTP server and model loading service after the main function starts to run?

### ISSUE THREAD

**Issue by muween** [tensorflow/serving#1756]
I need to add a service registration discovery function for tensorflow serving. In order to avoid that users cannot get the model through ip ( the http or grpc service are ready, but the model loading don't ), I must ensure that all threads are finished and then register the service.

**Comment by muween** [comment]
In other words, when status returns OK, are both service startup and model loading complete?

**Comment by rmothukuru** [comment]
@muween,
Can you please elaborate your question. Also include your TensorFlow Serving version. 

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by rmothukuru** [comment]
@muween,
Can you please respond to the above comment. Thanks!
