### ISSUE TITLE
tf.example During Serving

### ISSUE THREAD

**Issue by tgaddy** [tensorflow/serving#1834]
Please excuse me if this is the wrong place to post this. Doing it here because I think its related to problems with documentation and examples, but if there's a better place to ask this question I'd be grateful if someone could redirect me there :)

I'd like to understand why (if) I would want to use tf.examples during serving. 

In every example on the [TFX GitHub repo](https://github.com/tensorflow/tfx/tree/master/tfx/examples), the serving input function takes in serialised tf examples. In addition, on this page in the [TFS documentation](https://www.tensorflow.org/tfx/serving/performance) it states the following: 

> In general, it is advised to use the Classify and Regress endpoints as they accept tf.Example, which is a higher-level abstraction; however, in rare cases of large (O(Mb)) structured requests, savvy users may find using PredictRequest and directly encoding their Protobuf messages into a TensorProto, and skipping the serialization into and deserialization from tf.Example a source of slight performance gain.

However, in the actual examples on the [Tensorflow Serving GitHub](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/example/resnet_client_grpc.py), the example client code does not use tf examples and instead directly converts data to TensorProto. 

Why would I want to use tf examples during serving? I get why tf examples/tf.records make sense during training, but in general I find the API very difficult/annoying to work with and it just makes everything harder to reason about ([I don't think I'm the only one that feels this way](https://github.com/tensorflow/tensorflow/issues/29877)). The TFS documentation states that encoding protobuf messages into a TensorProto is for "savvy users", but honestly I find this much more understandable (just using `make_tensor_proto`) than the dozens of lines of boilerplate code that inevitably accompany tf.examples. I can't see how using tf.examples is a "higher level abstraction" or how it would make things easier on the client side. Feel like there's something fundamental I'm missing here that I can't find in any documentation for TFX or TFS?

I'd also be happy to help out with some documentation or examples here—if anyone thinks it's needed, perhaps I just missed something—I just need to understand a bit better first.

**Comment by singhniraj08** [comment]
@tgaddy,

The [Classify and Regress API](https://www.tensorflow.org/tfx/serving/api_rest#classify_and_regress_api) accepts list of [Example](https://github.com/tensorflow/tensorflow/blob/92e6c3e4f5c1cabfda1e61547a6a1b268ef95fa5/tensorflow/core/example/example.proto#L13) objects where as the [Predict API](https://www.tensorflow.org/tfx/serving/api_rest#predict_api) accepts input tensors in 0-th dimension or columnar format.

The [Performance Guide](https://www.tensorflow.org/tfx/serving/performance) suggests using PredictRequest over Classify and Regress for slight performance gain because the PredictRequest skips the serialization into and deserialization from tf.Example part. You can refer to [RESTful API](https://www.tensorflow.org/tfx/serving/api_rest) for request and response format for particular APIs. Thank you!
