### ISSUE TITLE
Is there an example or a document for golang or java calling tfs by grpc ?

### ISSUE THREAD

**Issue by DachuanZhao** [tensorflow/serving#1873]

**Comment by jurampark** [comment]
If you meant sending inference requests using grpc, it's possible in any supported languages by grpc because grpc is just about connecting channel with desired interface to the server. I just found this example from other's github repository. https://github.com/yu-iskw/tensorflow-serving-example/blob/master/python/grpc_mnist_client.py

**Comment by DachuanZhao** [comment]
> If you meant sending inference requests using grpc, it's possible in any supported languages by grpc because grpc is just about connecting channel with desired interface to the server. I just found this example from other's github repository. https://github.com/yu-iskw/tensorflow-serving-example/blob/master/python/grpc_mnist_client.py

Yes . there is a module named "tensorflow-serving-api" which make calling tfs by grpc convenient in python . However , there isn't a module in golang . Does the community plan to maintain modules which can make developer call tfs grpc convenient for golang , java and c# ?

**Comment by yonatankarni** [comment]
here's a blog post I was able to follow for making GRPC requests to tensorflow model server:
https://medium.com/@junwan01/a-java-client-for-tensorflow-serving-grpc-api-d37b5ad747aa

**Comment by arghyaganguly** [comment]
Closing this based on the previous comment by @yonatankarni .Please free to reopen if required.Thanks.
