### ISSUE TITLE
Servable Traits?

### ISSUE THREAD

**Issue by rayglover-ibm** [tensorflow/serving#190]
I noticed that the `tensorflow_model_server` naturally only supports the TensorFlow servable. It seems that the intended approach is for other servables to implement their own model_server, wrapping server_core where sensible.

Some servables are more similar than others, however. I've been working on Caffe support [here](https://github.com/rayglover-ibm/serving-caffe) which mimics the TensorFlow servable implementation. Since there are many similarities, it felt natural to modify the model server to be parameterized on traits of the servable. You can see this attempted [here](https://github.com/rayglover-ibm/serving-caffe/blob/caffe/tensorflow_serving/model_servers/main.cc#L108).

I believe this compositional approach would be beneficial to other parts, in particular the batching componentry, which the last time I looked was quite TensorFlow (and `tensorflow::Tensor`) centric.

Perhaps something else along similar lines has been considered before?

**Comment by chrisolston** [comment]
Yes, as you can see we've tried to be tensorflow-agnostic in most of our code, but at the same time haven't gone overboard with templating to support other kinds of ML models. Extending the model-server to be templetized for the kind of model is a good idea. An alternative approach to templates/traits would be to use a registry pattern. I mention that because inside google we have discussed moving to the registry approach for TF-Serving, although it hasn't bubbled to the top of our priority list yet which is why you haven't seen any movement there :)

I wouldn't want to block your progress so it would be great to move forward with the templates/traits approach. Looking forward to the contribution!

**Comment by rayglover-ibm** [comment]
Admittedly I've noticed the TensorFlow (and perhaps Google generally) avoid the template-all-the-things approach, meaning a registry system is probably more in keeping with the grand scheme of things.

In addition it may be feasible to add some build magic to allow people to plug-in their servable(s). My servable has support for something along these lines by allowing one to specify which fork of Caffe to build with, but I'm thinking more generally.

Anyway I thought I'd let it be known that I'm interested in such things as a means to leverage TensorFlow Serving as a generic model serving framework, and I'd adopt any move in that direction. It would also likely make any attempt to contribute additional servables less painful. :)
