### ISSUE TITLE
Why TF Serving GPU using GPU Memory very much?

### ISSUE THREAD

**Issue by duonghb53** [tensorflow/serving#1929]
## Bug Report
TFS using GPU Memory very much!

### System information
- **OS Platform and Distribution: CentOS 8.4, Cuda 11.4
- **TensorFlow Serving installed from: Docker
- **TensorFlow Serving version: lastest-gpu

### Describe the problem
I try install and run TFS with sample follow guide: _https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/docker.md_

After install done, I run TFS with sample: 
_docker run --gpus all -p 8501:8501 \
--mount type=bind,\
source=/tmp/tfserving/serving/tensorflow_serving/servables/tensorflow/testdata/saved_model_half_plus_two_gpu,\
target=/models/half_plus_two \
  -e MODEL_NAME=half_plus_two -t tensorflow/serving:latest-gpu &_

but GPU Memory Usage 22553MiB/24265MiB.
I don't know reason about this.
Please tell me about it?

### Source code / logs
![image](https://user-images.githubusercontent.com/10292938/139595374-498e2d65-1966-4393-8a64-fa42eb57f3d3.png)

Thank you!

**Comment by pindinagesh** [comment]
@duonghb53 

Could you please refer similar issues described in [link1](https://github.com/tensorflow/serving/issues/1440) and [link2,](https://github.com/tensorflow/serving/issues/1407) let us know if this helps. thanks

**Comment by shv07** [comment]
@pindinagesh 

I have also been facing this issue while deploying models with tf serving.

The gpu usage keeps increasing with increasing number of inference requests. And the used memory is not released after the request is over leading to the OOM error very soon when there are multiple models deployed on same gpu. 

Though this behavior is there with pure tensorflow-based (non TF-serving) deployment, I was expecting it would not be the case with TF Serving since it has been designed for optimized production deployment.

The link1, link2 were not of much help. Enabling gpu_growth (using ```TF_FORCE_GPU_ALLOW_GROWTH=true```) would lead to low gpu usage initially but finally end up with same issue as the no. of requests increase. And restricting gpu usage to a certain fraction will also not be a feasible approach where same gpu is used for deploying multiple models.

Is it possible to somehow release the unused gpu memory once an inference request is complete or some other way to tackle this issue?

**Comment by shv07** [comment]
Any updates on this?

**Comment by guanxinq** [comment]
The issue of not releasing unused memory is inherited from TF and currently there is no workaround. We will discuss it internally to see if we could fix it at least for TF serving.

**Comment by duonghb53** [comment]
> The issue of not releasing unused memory is inherited from TF and currently there is no workaround. We will discuss it internally to see if we could fix it at least for TF serving.

Thank you for response! I will waiting team resolve it.

**Comment by shv07** [comment]
> The issue of not releasing unused memory is inherited from TF and currently there is no workaround. We will discuss it internally to see if we could fix it at least for TF serving.
So, whatever additional memory pool keeps getting occupied by the TF serving, is that shared across all the models deployed in it? i.e. if I have a TF and a non-TF model deployed with TF-serving, will that memory pool be shared between both of them?

**Comment by singhniraj08** [comment]
@duonghb53,

Underneath the hood, TensorFlow Serving uses the TensorFlow runtime to do the actual inference on your requests. And by default, TensorFlow maps nearly all of the GPU memory of all GPUs (subject to [CUDA_VISIBLE_DEVICES](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#env-vars)) visible to the process. 

To mitigate this, currently we have a flag `"per_process_gpu_memory_fraction"` in [command-line flags](https://github.com/tensorflow/serving/blob/r2.0/tensorflow_serving/model_servers/main.cc#L162-L168) to define a fraction that each process occupies of the GPU memory space. Kindly let us know if this flag settles your high GPU usage.
Thank you!
