### ISSUE TITLE
CI is broken

### ISSUE THREAD

**Issue by apivovarov** [tensorflow/serving#1997]
All recent PRs are still awaiting CI build results

Some checks haven’t completed yet:
- Ubuntu CPU Expected — Waiting for status to be reported
- import/copybara Expected — Waiting for status to be reported

e.g. 
- https://github.com/tensorflow/serving/pull/1988 Mar 11, 2022
- https://github.com/tensorflow/serving/pull/1987 Mar 2, 2022

**Comment by guanxinq** [comment]
There was a GRPC build issue, which was fixed recently. The latest PRs triggers CI and the build succeeded.

**Comment by apivovarov** [comment]
is this project dead? I do not see any PRs reviewed and merged at all.

**Comment by singhniraj08** [comment]
@apivovarov,

Because of GRPC build issue, `Ubuntu CPU` and `import/copybara` were failing but the issue has been fixed and latest PRs triggers CI and the build succeeded.

Rest assured, the project is certainly not dead and we are working on issues and bugs. I will pass the above bugs to team for review and get some updates. Thank you!
