### ISSUE TITLE
Unable to buildTensorFlow Serving via Docker

### ISSUE THREAD

**Issue by vasantivmahajan** [tensorflow/serving#203]
I need to run TensorFlow Serving in windows, I followed the instructions from the following link: https://tensorflow.github.io/serving/docker.html.

However, on running the command "docker build --pull -t $USER/tensorflow-serving-devel -f Dockerfile.devel .", the following error is displayed.

![image](https://cloud.githubusercontent.com/assets/17990840/19286242/ed477b58-8fca-11e6-8c2b-900c57950207.png)

Any help is appreciated!

**Comment by kirilg** [comment]
Please look at the [tag name convention in Docker](https://docs.docker.com/engine/reference/commandline/tag/). The error message says that the tag is "/tensorflow-serving-devel", and "A name component may not start or end with a separator." It appears that Windows does not evaluate the $USER variable, so you'll need to manually expand that.

**Comment by vasantivmahajan** [comment]
@kirilg If "docker build --pull -t $USER/tensorflow-serving-devel -f Dockerfile.devel ." is not the correct image name (since it says its not a valid repository/tag), then what is the correct image name? \

Also, could you please explain the meaning of " It appears that Windows does not evaluate the $USER variable, so you'll need to manually expand that."

**Comment by kirilg** [comment]
It is the right command, but I'm saying that $USER was not resolved to your user name in Windows, so that's the problem. You can see that the command is 
`docker build --pull -t $USER/tensorflow-serving-devel -f Dockerfile.devel .` but the thing that actually ran was 
`docker build --pull -t /tensorflow-serving-devel -f Dockerfile.devel .`

Note that $USER/tensorflow-serving-devel was resolved to /tensorflow-serving-devel since $USER was not set. Try `docker build --pull -t vasantivmahajan/tensorflow-serving-devel -f Dockerfile.devel .`
and update future commands that use that tag accordingly.

**Comment by vasantivmahajan** [comment]
@kirilg: Thank you for your guidance. The problem was resolved by going to the directory where the Dockerfile.devel file was present and then running the command "docker build --pull -t vasantivmahajan/tensorflow-serving-devel -f Dockerfile.devel ."
