### ISSUE TITLE
Build Failing for 2.11.0

### ISSUE THREAD

**Issue by joydeb28** [tensorflow/serving#2098]
Trying to build docker with centos-7
here is the error I am getting
`# Configuration: e292c1b426707d92210aaeeec6878522fa818734fef6fdefa74bf597c73a3f24# Execution platform: @local_execution_config_platform//:platformduring RTL pass: expand
external/llvm-project/llvm/lib/Target/ARM/Thumb2InstrInfo.cpp: In function 'bool llvm::rewriteT2FrameIndex(llvm::MachineInstr&, unsigned int, llvm::Register, int&, const llvm::ARMBaseInstrInfo&, const llvm::TargetRegisterInfo*)':
external/llvm-project/llvm/lib/Target/ARM/Thumb2InstrInfo.cpp:764:1: internal compiler error: in commit_one_edge_insertion, at cfgrtl.c:2030
 }`
 
 CPU Config
 `
 Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                48
On-line CPU(s) list:   0-47
Thread(s) per core:    2
Core(s) per socket:    24
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Platinum 8167M CPU @ 2.00GHz
`
 Does anyone have any idea about this?

**Comment by singhniraj08** [comment]
@joydeb28,

At what point did you received this error? Could you please share with us the commands used to build custom image, so that we can try to replicate it on our end.

I tried building custom docker image and was able to run the commands successfully. I couldn't verify the complete build process, because building custom image is lengthly process.
Please follow [developing with docker](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/building_with_docker.md#dockerfiles)  tutorial while building docker file. Thank you!

<img width="1509" alt="Screenshot 2023-02-28 at 3 36 57 PM" src="https://user-images.githubusercontent.com/110809167/221844784-210745b8-2536-4bea-bcbc-5428190b81a2.png">

**Comment by bugwang** [comment]
yes  centos-7  ,  error:
external/llvm-project/llvm/lib/Target/ARM/Thumb2InstrInfo.cpp:766:1: internal compiler error: in commit_one_edge_insertion, at cfgrtl.c:2040

**Comment by bugwang** [comment]
centos-8
external/llvm-project/llvm/lib/Target/ARM/Thumb2InstrInfo.cpp:766:1: internal compiler error: in commit_one_edge_insertion, at cfgrtl.c:2040
