### ISSUE TITLE
APIs for TF Serving Profiling

### ISSUE THREAD

**Issue by ndeepesh** [tensorflow/serving#2149]
### Describe the problem the feature is intended to solve
Does TensorFlow serving provide APIs which can be used for profiling Tensorflow serving requests. I want to on-demand using a command line initiate a profiling session for `x` mins and then collect those logs to show them on tensorboard later.

Also is there any data on how much profiling affects TF Serving runtime latency? Does profiling also affects the tf ops time?

### Describe alternatives you've considered
Tried tensorboard but that does not fit my use case of on-demand low effort profiling

**Comment by singhniraj08** [comment]
@ndeepesh,

I couldn't find any specific API for profiling Tensorflow serving inference requests. TensorBoard's Profiling tool is pointed at  TensorFlow Serving's gRPC server. The Tensorboard UI will capture the traces of the inference request parallel to when an inference request is made. 
Also, the act of Tensorboard profiling should not affect the performance of TF Serving and served model as internally it used Tensorflow profiler to track the performance of your TensorFlow models. Although, running the Profiler for too long can cause it to run out of memory and it is recommended to profile no more than 10 steps at a time. Avoid profiling the first few batches to avoid inaccuracies due to initialization overhead.

As an alternative you can try to monitor TF serving with Prometheus. to enable prometheus monitoring, you can provide a monitoring configuration to the server by using the --monitoring_config_file flag to specify a file containing a [MonitoringConfig](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/config/monitoring_config.proto#L17) protocol buffer as shown [here](https://www.tensorflow.org/tfx/serving/serving_config#monitoring_configuration). I found an [article](https://itnext.io/monitor-deployed-tensorflow-models-with-prometheus-and-grafana-28d6135a2666)  with step by step process to enable prometheus monitoring in TF Serving.

Thank you!

**Comment by ndeepesh** [comment]
Thanks @singhniraj08. Couple of follow up questions
1. I saw this (https://github.com/tensorflow/serving/blob/6623fe587207fc91615cd7214ff56bad32574b0c/tensorflow_serving/model_servers/profiler_client.py#L23) profiler_client in tensorflow_serving github repo. Can I use this on the box where tensorflow serving is running? For instance lets say I know which port tf serving is running locally, I can use this client to point to localhost:port to get metrics. Right? Am I understanding this correctly?
2. Prometheus metrics wont give in depth details on each ops time. Right? Where can I see what metrics are exposed by prometheus?

**Comment by ndeepesh** [comment]
@singhniraj08 Any updates on above questions?

**Comment by singhniraj08** [comment]
@ndeepesh,

Apologies for late reply. `profiler_client` in tensorflow serving is used by Tensorboard profiling tool to profile data. I am not sure wether the steps you mentioned will work. Also, I could find any documents to point to for metrics which are exposed by prometheus in TF Serving.
@yzy0004, Could you please help here with some pointers on TF Serving monitoring.

**Comment by yzy0004** [comment]
The profiler_client will initiate the on-demand profiling and log all the metrics in the given TensorBoard directory.

And the Prometheus, according to the doc, will record both serving and core tensor flow metrics, which are defined separately. So I am not sure if the ops time is part of those.

**Comment by ndeepesh** [comment]
Thanks @yzy0004 Where can I find more information on what metrics are exposed by Prometheus?

**Comment by ndeepesh** [comment]
@yzy0004 Another question on TF Serving Profiling - If there are multiple models running behind a serving process how do we identify which model is being profiled? Or would the profiled results include all those models?

**Comment by ndeepesh** [comment]
@yzy0004 @singhniraj08 Can you please help above questions?

**Comment by singhniraj08** [comment]
@ndeepesh,

For multiple models, metrics will be generated for all the models with model name defined in metrics. I couldn't find any document for the list of metrics exposed to Prometheus. #1623 have few list of metrics last added if this helps. Thank you!
Example metric:
```
:tensorflow:serving:runtime_latency_bucket{model_name="test_model",API="Predict",runtime="TF1",le="18"} 0
:tensorflow:serving:runtime_latency_bucket{model_name="test_model",API="Predict",runtime="TF1",le="32.4"} 0
```

**Comment by ndeepesh** [comment]
@singhniraj08 Is this for Prometheus metrics? Or model profiling via the TF profiler?

**Comment by singhniraj08** [comment]
@ndeepesh, It is for Prometheus metrics. Thanks.
