### ISSUE TITLE
When my model exceeds the maximum capacity of a single gpu, can I fragment the model to multiple gpu?

### ISSUE THREAD

**Issue by for1314ai** [tensorflow/serving#2159]
When my model exceeds the maximum capacity of a single gpu, can I fragment the model to multiple gpu?

**Comment by singhniraj08** [comment]
@for1314ai,

TF Serving only executes the graph loaded. If you graph is using multiple GPUs TF serving will use them, if you graph is only using one GPU (most common case) then you will be able to run it in one GPU in TF Serving. 
Probably your best solution is to build a script which loads your graph once per GPU, then uses some code in the CPU to split the batch data into the GPU graphs and finally export the whole graph with support for multiGPU.

Similar feature request #311 and #1588 were also filled in past but couldn't make it because of not enough community support. Alternatively, you can follow this amazing tutorial for [Serving multiple ML models on multiple GPUs with Tensorflow Serving](https://stephenweixu.medium.com/serving-multiple-ml-models-on-multiple-gpus-with-tensorflow-serving-fe2ade7aa16b).
Kindly let us know if the above approach works for you, else we can consider this feature request. Thank you!
