### ISSUE TITLE
Scriptable pre ./configure almost works

### ISSUE THREAD

**Issue by villasv** [tensorflow/serving#216]
I'm trying to automate the build process of a tensorflow serving docker image, adding the `bazel-build` for the model server in the provided Dockerfile.
The problem is after cloning the `serving` repo we have to configure it, and while most configuration steps can be pre-answered with env variables like

```
RUN export PYTHON_BIN_PATH=/usr/bin/python && \
    export TF_NEED_GCP=0 && \
    export TF_NEED_HDFS=0
```

The configuration of the python libs controlled by `util/python/python_config.sh` can only be achieved with normal input.
I know this is actually an issue in `tensorflow` instead of `serving`, if I make a PR there I'll reference this one.

**Comment by villasv** [comment]
The PR just got merged. I could make a PR here just to update the refs, but I guess you guys do it by yourselves regularly so I'll just wait for it and close it right after :-)

**Comment by kirilg** [comment]
We updated the TF submodule to point to [this commit](https://github.com/tensorflow/tensorflow/tree/d9a89a5cf63b2ecedf68d3eefdc24be3f519e503) so your change should be included.

I'll close this issue since you should be unblocked to automatically configure in a script. Please re-open if anything is broken.
