### ISSUE TITLE
Increased memory usage on TF 2.11

### ISSUE THREAD

**Issue by ndeepesh** [tensorflow/serving#2179]
Hello,

We are seeing that TF 2.11 is continuously seeing higher memory footprint compared to TF 2.4 on same model. Is this expected?

For instance we are seeing ~1.6GB of memory occupied by model on TF 2.11 compared to ~400MB on TF 2.4

**Comment by singhniraj08** [comment]
@ndeepesh,

Are you able to replicate this issue with [half_plus_two](https://github.com/tensorflow/serving/tree/master/tensorflow_serving/servables/tensorflow/testdata/saved_model_half_plus_two_cpu/00000123) or any other example model?  Also, Are you sending the requests in [batching](https://www.tensorflow.org/tfx/serving/serving_config#batching_configuration)? Batching helps in lesser memory usage. 

If the example setup helps us replicate the issue on our end, we can try to pin point the root cause of this issue and resolve it. You can also follow this [article](https://www.mux.com/blog/tuning-performance-of-tensorflow-serving-pipeline) which guides in improving TF Serving performance. Thank you!
