### ISSUE TITLE
TF Serving batching for Sparse Tensors

### ISSUE THREAD

**Issue by ndeepesh** [tensorflow/serving#2188]
Is there a way to use TF Serving server side batching (via --enable_batching) for sparse tensors? I saw this old issue but could not find a solution there - https://github.com/tensorflow/serving/issues/883

Getting - `"Batching session Run() input tensors must have equal 0th-dimension size"`

**Comment by ndeepesh** [comment]
@singhniraj08 Can you please help with above?

**Comment by singhniraj08** [comment]
@ndeepesh,

Apologies for late reply. Going through the old issue, TF Serving batching capability only supports dense tensors and sparse tensors are not supported yet. TensorFlow represents sparse tensors through the [tf.sparse.SparseTensor](https://www.tensorflow.org/api_docs/python/tf/sparse/SparseTensor) object which is not supported in TF Serving batching.

One workaround I can think of is to convert the sparse tensor to dense tensor using [tf.sparse.to_dense](https://www.tensorflow.org/api_docs/python/tf/sparse/to_dense) before sending it to your model. Let us know if this works for you. Thank you!

**Comment by ndeepesh** [comment]
Hi @singhniraj08 Thanks for your reply. Our TF model accepts those sparse tensors so that would require
1. Changing the model to accept dense tensors instead of sparse.
2. Sending sparse tensors over network compared to dense tensors improves I/O.

Followup Question:
1. Lets say TF serving is running as a separate process with GPUs enabled. Does batching happens on CPU or GPU? If batching happens on GPU then I am thinking can Batching session convert sparse tensors to dense tensors (essentially execute the initial part of graph) and then produce batches? Is this feasible? Or if there is a way to do it - I am happy to contribute

**Comment by singhniraj08** [comment]
@ndeepesh, Tensorflow model graph utilizes the GPU and batching being a preprocessing step will happen in CPU. 

I am not sure if sparse to dense transformation can be implemented on the batching side(as model server code is written in C++), implementing support of sparse tensors in TF Serving will make more sense. I understand your idea of converting spare to dense tensors during preprocessing step but in this case also, you would have to make changes in your model to accept dense tensor instead of sparse tensors. 
And if you are concerned about the network latency, you are go through this [article](https://www.mux.com/blog/tuning-performance-of-tensorflow-serving-pipeline#improving-speed-on-prediction-client) which can help you improve the TF Serving performance. Thanks.
