### ISSUE TITLE
Difference between Metrics emitted by TF Serving

### ISSUE THREAD

**Issue by ndeep27** [tensorflow/serving#2208]
What is the difference between below metrics that are emiited by TF Serving and TF Core?

/tensorflow/serving/request_latency - [Here](https://github.com/tensorflow/serving/blob/0f8be393d694137c0f1129e80b385a7a8c9c067e/tensorflow_serving/servables/tensorflow/util.cc#L83)
/tensorflow/serving/runtime_latency - [Here](https://github.com/tensorflow/serving/blob/0f8be393d694137c0f1129e80b385a7a8c9c067e/tensorflow_serving/servables/tensorflow/util.cc#L73)
/tensorflow/core/graph_run_time_users_historgram - [Here](https://github.com/tensorflow/tensorflow/blob/5b29cd2a5f6dd2220b1cafacf50b46b467e51c8f/tensorflow/core/framework/metrics.cc#L54C7-L54C69)

Lets say we are running TF model on GPU. What all is involved between request_latency, runtime_latency and graph_runtime? For instance gRPC ser/de might be involved but what else is involved? We are seeing difference between request and runtime latencies for GPU serving but for CPU serving this difference is negligible

**Comment by singhniraj08** [comment]
@ndeep27,

`Request Latency` would account the time taken by Tensorflow Serving to process the request and send predictions. This includes waiting for resources, input/output operations, or other processes. 

`Runtime Latency` would account the time taken by Tensorflow runtime within Tensorflow Serving to process the request and generate predictions.

The difference between metrics of using GPU and CPU might be because of the fact that the overhead of invoking GPU kernels, and copying data to and from GPU, is very high. For operations on models with very little parameters it is not worth of using GPU since frequency of CPU cores is much higher.

Thank you!
