### ISSUE TITLE
bazel build tensorflow_serving/...  no such package 'inception'

### ISSUE THREAD

**Issue by grzesir** [tensorflow/serving#25]
I'm trying to build tensorfolw_serving on OSX El Capitan and keep getting an error. I installed Bazel through homebrew.

Here is the error:
`$ bazel build tensorflow_serving/...`
`Extracting Bazel installation...`
`............`
`ERROR: /private/var/tmp/_bazel_robertgrzesik/fb4fbbbabd0582fe8f5abe6ab13dbfd9/external/inception_model/inception/slim/BUILD:93:1: no such package 'inception': BUILD file not found on package path and referenced by '@inception_model//inception/slim:slim'.`
`ERROR: Loading failed; build aborted.`
`INFO: Elapsed time: 45.554s`

I also tried giving it the package path on my system and got a different error:
`$ bazel build --package_path /Users/robertgrzesik/anaconda/lib/python2.7/site-packages tensorflow_serving/...`
`ERROR: no targets found beneath 'tensorflow_serving'.`
`INFO: Elapsed time: 0.131s`

**Comment by grzesir** [comment]
I installed Bazel through the download off their website and worked properly.

Here's a link: http://bazel.io/docs/install.html

Seems that installing from homebrew causes some errors.

**Comment by kirilg** [comment]
Not sure why installing through homebrew should cause bazel to not find inception, unless it's an older version. Could you run `bazel version` to verify you're using 0.2.0.

If you are, I wonder if it just can't find inception or if it wouldn't be able to find any local_repository. Could you try running
`bazel build @tf//tensorflow/core:lib` to confirm it can find TensorFlow.

By the way, if you're using homebrew because you're on Mac, keep in mind that there is other stuff that will likely not work - https://github.com/tensorflow/serving/issues/1

**Comment by kirilg** [comment]
Note that if you are running on Mac, even though we don't yet have full support for it, it does work if you run it in a docker container - http://tensorflow.github.io/serving/docker
