### ISSUE TITLE
tf.initialize_all_tables() and tf.initialize_all_variables() as single init op

### ISSUE THREAD

**Issue by prats226** [tensorflow/serving#258]
I am importing an existing graph in my code which has some tables to initialise and my code has some variables. Since I need to pass init op to Exported, I tried grouping these two ops but still it demands a single op with error `load failure: Failed precondition: Expected exactly one serving init op`

**Comment by chrisolston** [comment]
At this time you need to pass a single node. If you don't need the two ops to execute in a particular order you can use the tf.group op. Otherwise you may need to create a custom op that invokes the other two ops, and introduce a control dependency via tf.control_dependencies (not sure about the need for a custom op in this case; maybe consult the main tensorflow documentation / discussion forum?).

We are aware that this is cumbersome, and are hoping to get to a better solution soon.

**Comment by sukritiramesh** [comment]
Hi @prats226, as @chrisolston suggested, it looks like using tf.group or tf.control_dependencies may have resolved the issue here.

(Closing this issue for now, but please feel free to reopen if the issue persists. Thanks!)
