### ISSUE TITLE
Depends on TensorFlow release version

### ISSUE THREAD

**Issue by llhe** [tensorflow/serving#291]
In our use case, we made some necessary customization over the original tensorflow code and forked to internal branches. However, the serving project looks like depends on an arbitrary tensorflow commit. This make it really difficult to build our customized serving project because it's hard to find a proper customized tensorflow commit except make the integration against this arbitrary commit which serving depends.

From engineering perspective, it's also better to depends on a stable version of tensorflow.

**Comment by kirilg** [comment]
It's often necessary to make changes that simultaneously modify TF and TF Serving (e.g. update an API), and that impacts how those changes get pushed to GitHub later. Depending on the last stable TF version will not always be feasible because these cross-repo changes will need to be pushed together, and the TF commit we depend on updated.

We currently depend on a TF commit that passed the nightly tests corresponding to our last push, so it's not exactly arbitrary, but not as strict as "only depend on known releases".

----
For your use case of making custom changes to TensorFlow, you may want to do one of:
- Submit your changes to TensorFlow and wait for them to be propagated into TensorFlow Serving.
- Create your own fork of TensorFlow that includes your changes, and make TensorFlow Serving depend on that instead of the main branch of TensorFlow. This will still run into issues when TensorFlow makes API changes that require an update to TF Serving, but it should not be common common. If that happens, you'll just need to pull the latest TF changes into your fork and possible merge conflicts.

**Comment by llhe** [comment]
Thanks @kirilg
