### ISSUE TITLE
Tensorflow Serving basic example fails without --use_saved_model=false 

### ISSUE THREAD

**Issue by ras44** [tensorflow/serving#308]
I'm unable to run the 'Test the Server' code 
```
$>bazel-bin/tensorflow_serving/example/mnist_client --num_tests=1000 --server=localhost:9000
```
shown in the [basic example ](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/serving_basic.md) without producing the error: 

```
AbortionError(code=StatusCode.NOT_FOUND, details="FeedInputs: unable to find feed output images")
```

I've provided the steps that I've followed [here](http://stackoverflow.com/questions/41721526/tensorflow-serving-basic-example).

I can successfully test the server if I including the option `--use_saved_model=false` when starting the server, but I'm not certain this is the correct solution.

**Comment by lilao** [comment]
Can you retry the example and make sure that you execute "rm -rf /tmp/mnist_model" before exporting the model using mnist_saved_model.py? If you have an old export that was produced by mnist_export.py, it will not be compatible with mnist_client.py, due to our recent change in mnist_client.py to switch to the new export format (SavedModel).

**Comment by ras44** [comment]
@lilao it looks like removing the directory and rebuilding worked- thanks for your help
