### ISSUE TITLE
Docker FROM tensorflow image

### ISSUE THREAD

**Issue by bhack** [tensorflow/serving#393]
Instead of handling tensorflow as a submodule is it not better to derive the dockerfile FROM a tensorflow image?

**Comment by kirilg** [comment]
That has some advantages, but at least the last time we discussed this with the TensorFlow team, TensorFlow did not release installed packages of everything we'd need to link in to compile TF Serving. The python libraries can be installed with pip install, but TF Serving depends on C++ code that's not available in that package.

If it was available, it would be possible to do so but might still make some things more challenging for us. For example, there are times when a single change affects both repos (e.g. a change to a TF function + all callers of it). In such a scenario, now we'll just wait for the TF change to propagate to GitHub and update the submodule commit. If we depended on an image, we'd need to require everyone to reinstall from the most recent nightly build or otherwise serving won't compile.

I think a good option is for TF Serving to also release binaries, and it's something we're thinking about.

**Comment by bhack** [comment]
But you can always from the TF dev docker image (or something similar) instead of the pip one so

**Comment by kirilg** [comment]
Not sure I fully understand the workflow. What would users of TF Serving have to do to make it work with the docker image if TF is not a submodule? We need all C++ targets to properly link and have it be intuitive enough to use.

Right now it's intuitive, you run `git clone --recursive` and you get everything you need (though I understand it takes a while to compile and sometimes people run into issues). What will the install story be if we use TF as a docker container? Will we have to tell users to go install Docker and get the latest dev container (or from a specific date because latest doesn't always work) to get things building? It sounds like it's more complicated and error-prone than using a submodule, but maybe I'm misunderstanding.

**Comment by bhack** [comment]
Dockerfile are composable so we could start FROM an image from TF dockerhub (pushed by tensorflow serving team) and just compile or run TF serving. If somebody want to build again TF source he could go ahead with with git clone --recursive and rebuild TF+serving.
