### ISSUE TITLE
How to transform a  common model that  do not export the parameters of input and output for tensorflow serving?

### ISSUE THREAD

**Issue by chris0927** [tensorflow/serving#424]
When   trainning  the example of mnist ,add export function.If I have the model  that do not add export function.How to tansform ?

**Comment by kirilg** [comment]
If I understand the question correctly, you'll have to export your model in order to be able to serve it. See our [serving_basics](https://tensorflow.github.io/serving/serving_basic) tutorial and the [SavedModel README](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/saved_model/README.md) for more details on how to do that.
