### ISSUE TITLE
Using classes with predict_signature_def

### ISSUE THREAD

**Issue by viksit** [tensorflow/serving#450]
When using `classes` in the following,

```
# class_list = ["a", "B", ...]
class_tensor = tf.constant(class_list)
indices = tf.constant(list(range(0,len(class_list))))
table = tf.contrib.lookup.index_to_string_table_from_tensor(class_tensor)
classes = table.lookup(tf.to_int64(indices))

signature = predict_signature_def(inputs={"input": inputs},
                                  outputs={
                                  "scores": outputs,
                                  "classes": classes})
```

I get the following error,

```
{
  "error": "Prediction failed during encoding instances"
}
```

Without the classes key though, I get the output back just fine. What could be causing this? All examples in the repo seem to use `signature_def_utils.build_signature_def()` vs just `predict_signature_def`, so I'm not sure what could be going wrong here.

**Comment by kirilg** [comment]
build_signature_def() takes inputs and outputs as maps of string_key->TensorInfo protos.
predict_signature_def() takes inputs and outputs as dicts of type Tensor. It builds TensorInfos out of Tensors, and if there is one input and one output, standardizes the keys to "inputs" and "outputs" (compare that to your keys of "input", "scores", and "classes"). I suspect there is a mismatch of keys in the output which changes to "outputs" when you remove scores because then you're down to just one tensor.

Where are you getting the error "Prediction failed during encoding instances"? Is this at training time, at request time when querying the model that's loaded in a model_server? If that latter, could you also include a sample request?

**Comment by sukritiramesh** [comment]
Closing given @kirilg's response; please reopen if required.

**Comment by viksit** [comment]
@kirilg @sukritiramesh would you have comments on a related issue being faced in https://github.com/tensorflow/models/issues/1811

**Comment by slothkong** [comment]
@kirilg man,how do you learn this stuff. The online docs have a chapter about building signatures?  I havent even been able to read the definition of signature in this context, and this helper functions `build_signature_def()` and `predict_signature_def() ` only have tiny docs inside the tensorflow source code ㅇㅅㅇ
