### ISSUE TITLE
Import error when trying to use grpc to generate codes for .proto file

### ISSUE THREAD

**Issue by atomextranova** [tensorflow/serving#473]
I  tried to generate py file for example shown in ```https://github.com/tensorflow/serving/tree/master/tensorflow_serving/apis ```

When I try to use the command(The files are kept locally under /home/username/test/serving/tensorflow_serving/apis (absolute path))

` -m grpc_tools.protoc -I/home/username/test/serving/tensorflow_serving/apis --python_out=. --grpc_python_out=. /home/username/test/serving/tensorflow_serving/apis/prediction_service.proto`

and also 
```python -m grpc.tools.protoc --python_out=. --grpc_python_out=. -I. tensorflow_serving/apis/prediction_service.proto```

to generate python codes. Neither versions of import below worked for me.

Version1:
```
import "/home/yifan/test/serving/tensorflow_serving/apis/classification.proto";
import "/home/yifan/test/serving/tensorflow_serving/apis/get_model_metadata.proto";
import "/home/yifan/test/serving/tensorflow_serving/apis/inference.proto";
import "/home/yifan/test/serving/tensorflow_serving/apis/predict.proto";
import "/home/yifan/test/serving/tensorflow_serving/apis/regression.proto";
```

Version2(google sample codes):
```
import "tensorflow_serving/apis/classification.proto";
import "tensorflow_serving/apis/get_model_metadata.proto";
import "tensorflow_serving/apis/inference.proto";
import "tensorflow_serving/apis/predict.proto";
import "tensorflow_serving/apis/regression.proto";
```

They both give me error messages like:
```
/home/yifan/test/serving/tensorflow_serving/apis/classification.proto: File not found.
/home/yifan/test/serving/tensorflow_serving/apis/get_model_metadata.proto: File not found.
/home/yifan/test/serving/tensorflow_serving/apis/inference.proto: File not found.
/home/yifan/test/serving/tensorflow_serving/apis/predict.proto: File not found.
/home/yifan/test/serving/tensorflow_serving/apis/regression.proto: File not found.
prediction_service.proto: Import "/home/yifan/test/serving/tensorflow_serving/apis/classification.proto" was not found or had errors.
prediction_service.proto: Import "/home/yifan/test/serving/tensorflow_serving/apis/get_model_metadata.proto" was not found or had errors.
prediction_service.proto: Import "/home/yifan/test/serving/tensorflow_serving/apis/inference.proto" was not found or had errors.
prediction_service.proto: Import "/home/yifan/test/serving/tensorflow_serving/apis/predict.proto" was not found or had errors.
prediction_service.proto: Import "/home/yifan/test/serving/tensorflow_serving/apis/regression.proto" was not found or had errors.
prediction_service.proto:18:16: "ClassificationRequest" is not defined.
prediction_service.proto:18:48: "ClassificationResponse" is not defined.
prediction_service.proto:21:15: "RegressionRequest" is not defined.
prediction_service.proto:21:43: "RegressionResponse" is not defined.
prediction_service.proto:24:15: "PredictRequest" is not defined.
prediction_service.proto:24:40: "PredictResponse" is not defined.
prediction_service.proto:27:22: "MultiInferenceRequest" is not defined.
prediction_service.proto:27:54: "MultiInferenceResponse" is not defined.
prediction_service.proto:30:24: "GetModelMetadataRequest" is not defined.
prediction_service.proto:31:16: "GetModelMetadataResponse" is not defined.
```
After that, what if I want to generate codes for my own proto file? Then what should I do?

**Comment by mountaintom** [comment]
Hi,

It looks like you pointed your include search path a little too far down the tree. Also, if I recall, the protos in TensorFlow Serving will try to include protos from TensorFlow. Because of the way the TensorFlow code is imported into the TensorFlow Serving code tree, it will be out of alignment with the includes in the proto's code. So, you ned to include another search path to find them.

You may want to try this include:
-I/home/username/test/serving:/home/username/test/serving/tensorflow

Here are some additional observations. As I have not yet had the chance to explore the python versions of the proto code generation, some of these items may be handled differently than my C++ experience. 

I compiled the proto files using the protoc compiler. In that case, the protoc compiler needed to be run on each proto file and once again with the gprc plugin on the prediction_service.proto file. Possibility the Python "grpc.tools.protoc" does more automatically for you. 

At least for the C++ environment, there is another, unique to TensorFlow, compiler for creating additional "proto text" files from the proto files. 

The protocol buffer and grpc generated files rely on additional support code from the TensorFlow source tree to implement them. Python may be less dependent on classes like "Tensor" than the C++ code, as the python code reimplements many things on its own with NumPy. 

Here is a link to creating TensorFlow Serving C++ clients, with a pruned down code tree, outside of the Bazel build environment. Something here may help you navigate your python scenario.
https://github.com/mountaintom/serving/tree/create-makefile-serving-client

**Comment by atomextranova** [comment]
Going to try to see if it works. Thanks for your detailed reply!
