### ISSUE TITLE
Using tensorflow serving as a distributed system

### ISSUE THREAD

**Issue by yqzhang** [tensorflow/serving#49]
I'm trying to figure out how I can set tensorflow serving up as a distributed system, in which multiple models can be served simultaneously, and each model can be served by multiple machines.

I found [this instruction](https://www.tensorflow.org/versions/r0.8/how_tos/distributed/index.html) about how tensorflow can be used as a distributed system, but it requires the client application to explicitly list all the servers involved. I wonder if there is something like a unified "frontend" to coordinate all the models and machines (if it is supported to run tensorflow serving as a distributed system). For example, a user query can be routed to the "frontend" machine with some specifications about what model it needs to run, and the "frontend" machine can figure out where the backend model is deployed and route the query to the machine.

Since tensorflow serving is a service-oriented framework, I'm guessing there probably already exists some support to scale it up to multiple server nodes.

Thanks!

**Comment by fangweili** [comment]
[This instruction](https://tensorflow.github.io/serving/serving_inception) has a very basic setup for end-to-end distributed serving.

We don't currently have the "frontend/controller" for more sophisticated use cases. Community contribution are encouraged/welcomed, and we are happy to provide assistance.

**Comment by viksit** [comment]
@chrisolston and I were having this discussion on another thread and will continue here since this just got opened.

There are a few things I can think of that would be needed here for this to work,

- Each server needs to be able to serve more than one model
- Models would have to be load balanced across servers, and a Chord style DHT to help direct them to an appropriate machine.
- Requests would have to have a modelId and invoke this DHT system to direct a response to an appropriate server.
- And everything needed to coordinate this :)

**Comment by yqzhang** [comment]
@fangweili Thank you for the quick reply. Does that mean it can only be used as a distributed system when I am using some kind of virtualization (e.g., docker)? It wouldn't work on native system?

**Comment by fangweili** [comment]
It can work on native system. It's just that the only distributed serving example we have now uses k8s, for simplicity purpose.

**Comment by xiaoweiw** [comment]
I noticed that the tutorial "serving inception model" uses kubernetes and multiple replicas are created via the replication controller. But how does TensorFlow Serving support communications in a distributed serving system with heterogeneous servers (different servers running different models)? Are there any specific mechanisms or interfaces?

**Comment by chrisolston** [comment]
Currently there are no mechanisms or interfaces for distributed TF-Serving. Contributions welcome :)

**Comment by jyotiskab** [comment]
Hi All,

I'm looking to set up Kubernates without leveraging google cloud platform, so I can have my distributed Tensorflow serving within my internal network (5 nodes, all with GPU support). I'm using the following as my guide: https://tensorflow.github.io/serving/serving_inception. Since I want to avoid using google cloud engine, my approach is to set up using the Bare-metal approach in my ubuntu servers. This is the tutorial: http://kubernetes.io/docs/getting-started-guides/ubuntu/

I'm a beginner with Kubernates, and I wanted to verify my approach. 

Thanks

**Comment by kirilg** [comment]
I've never manually deployed Kubernetes on Ubuntu nodes, but your approach sounds reasonable. I don't think we're aware of any known issues, so you can give that a try and follow up with either us or the Kubernetes team if you encounter any issues.

**Comment by jyotiskab** [comment]
Thanks! I will definitely try it. Lastly, me just also ask (bump to original question), is it possible to implement a distributed Tensorflow serving natively without docker/kubernate (maybe only utilize Apache Spark and Tensorflow Distributed)?

**Comment by kirilg** [comment]
We haven't tried this ourselves yet, so far we've only tested using Kubernetes, but I think some members of the community got it to work with Apache Spark - e.g. https://github.com/tensorflow/serving/issues/10. I only have the details mentioned in that issue, but it seems like it worked (the issue was primarily with batch scheduler tuning).
