### ISSUE TITLE
batching error when two inputs with different size

### ISSUE THREAD

**Issue by baicwang** [tensorflow/serving#494]
My model have two inputs, one is the input image, the other one is a scalar indicated training/testing phase. When batching open, the server always throw following error:
 details="Batching session Run() input tensors must have at least one dimension")

Any solution for this question？ does that mean tf serving do not support scalar input？

**Comment by chrisolston** [comment]
TF Serving does support scalar input, but you must disable batching. Batching works by concatenating tensors along the first dimension. If you have scalars that cannot be done.

If you want batching you need to restructure your graph so that every node is able to process a tensor whose first dimension is the batch size. So convert your scalar into a vector, and have your inputs be vectors of length 1, so the batcher can concatenate them into vectors of length B = batch size.
