### ISSUE TITLE
[Feature Request]Include make_tensor_proto, MakeNdarray in the tensorflow-serving-api pip package to remove dependency on Tensorflow

### ISSUE THREAD

**Issue by yjmade** [tensorflow/serving#557]
Currently, to build a client to build requests to tf-serving, people need to use `make_tensor_proto()` to convert a data(can be numpy array or string) to TensorProto, then use  `MakeNdarray()` to convert a TensorProto from outputs of the respond into numpy array. 
 Since the client is neither doing training or inferencing, this two function is the only thing import from Tensorflow package that is needed. so it's an good idea to remove the dependance of Tensorflow to make it thiner. 
More importantly, `import tensorflow` alone take 1.5s, and `from tensorflow.contrib.util import make_tensor_proto, MakeNdarray` takes 7.6s for the overhead of import everything inside tf.contrib, use `from tensorflow.python.framework.tensor_util import make_tensor_proto, MakeNdarray` is much quicker but still takes 1.98s. 
By putting this two function in `tensorflow-serving-api` package, the client doesn't need to import tensorflow any more. The startup time can be much shorter and the memory usage of the Tensorflow is just saved.

**Comment by kirilg** [comment]
tensorflow-serving-api is a very thin package that only includes the ModelServer API. If we were to include all of our TF dependencies inside of it, I believe we would also need to include all TF protos that we depend on in the API like `tensorflow.Example` or `SignatureDef` (admittedly still a fairly small list). Off the top of my head, I'm not sure how it would interact if you also have TF installed on your machine and now have conflicting imports from tensorflow.

Also because `make_tensor_proto` and `MakeNdarray` are not in this repo and we don't have full control over it, it feels uncomfortable to include it in our public API. These are meant to be helpful utility functions for building protos, and it's only the actual protos that are a part of our external API.

My personal preference is to keep them separate, but I understand it seems very heavyweight to include all of TF just to get a few functions/protos.

**Comment by dimpavloff** [comment]
Hi, 

Has your position changed regarding the above? I agree with @yjmade, it is burdensome for a service to have to import `tensorflow` just so that it can do inference with TF Serving because often such services contain normal business logic rather than ML/data libraries. 

> it's only the actual protos that are a part of our external API.
With this in mind, will it be possible to either move out the "public" protos which the `tensorflow` package provides (such as `TensorProto`) to a separate pypi package that both `tensorflow` and `tensorflow-serving-api` can depend on, or alternatively, adjust the TF Serving Inference RPC to be able to optionally take as `input` a proto provided by the `tensorflow-serving-api` package itself and then the RPC can internally translate it to a TensorProto if it needs to.

**Comment by gautamvasudevan** [comment]
There is now a RESTful API you can use that doesn't require tensorflow.

**Comment by aidandunlop** [comment]
We're have the same issue and we want to reduce the size of our container. We are required to only use gRPC so a RESTful API isn't helpful to us - is there another way to only import these functions?
