### ISSUE TITLE
Tensorflow serving error after version update

### ISSUE THREAD

**Issue by fromradio** [tensorflow/serving#572]
Hi all, I came across a strange problem applying tensorflow serving. I successfully ran tensorflow-serving on 20 servers and I update the model by accumulating the version.  18 servers auto-loaded the new model and worked fine. But 2 servers got the following error:

```
gRPC call return code: 9:Attempting to use uninitialized value wide_params/wide_bias
         [[Node: wide_params/wide_bias/read = Identity[T=DT_FLOAT, _class=["loc:@wide_params/wide_bias"], _output_shapes=[[1]], _device="/job:localhost/replica:0/task:0/cpu:0"](wide_params/wide_bias)]]
```

Does anyone has any idea?

**Comment by cfregly** [comment]
can you provide more detail on how you are deploying the new model?  shared file system?  are you deploying a tar bundle?  RSYNC'ing a directory to each node?

in general, i stay away from mutable deployments for exactly this reason.  

if there isn't a compelling reason to be mutable, can you restart the processes and point to the new model after a successful copy?

or deploy as an immutable container?

otherwise, you may want to build a custom model loader.

or at least add monitoring to your deployment process to make sure all servers have successfully loaded the new model.  (don't go this route)

**Comment by fromradio** [comment]
@cfregly thx for your advice

We deploy the new model by rsync'ing tar bundle from training machine. And we directly untar it to the final directory. We solve the problem by first untaring it to a temp dir and then mv it to the final dir.

I think the problem is caused by reading data before it is uncompressed.

**Comment by chrisolston** [comment]
I see. TF-Serving expects the saved-model bundles to arrive atomically. Doing a mv from a temp dir is one way to accomplish that. Glad your problem got fixed.
