### ISSUE TITLE
Pip installing with GPU support

### ISSUE THREAD

**Issue by maciejjaskowski** [tensorflow/serving#573]
I couldn't find a single word about how to install tensorflow-serving with GPU support. nvidia-smi shows that my installation of tensorflow-serving does not use GPU. 

Is there an yet undocumented way to do it or should i stick to building tensorflow-serving manually ?

**Comment by DIT4FUN** [comment]
may be it depend on which type of tensorflow you install,if you install tensorflow gpu version,maybe tensorflow-serving will using GPU

**Comment by kirilg** [comment]
The PIP package only contains the Python API. No need for GPU support there since it's simply a collection of protos to be used by Python clients.

The apt-get package of the ModelServer is something that can be compiled with GPU support, but we don't offer a pre-built version (https://github.com/tensorflow/serving/issues/549) so you'll have to build manually like you said.
