### ISSUE TITLE
Reason tf_models/research/slim/BUILD includes explicit dependency on //tensorflow recently?

### ISSUE THREAD

**Issue by gyang274** [tensorflow/serving#628]
I am adding slim-inception-v4 into tensorflow serving examples. I found the slim BUILD file was recently updated with several libraries include a explicit dependency to tensorflow, e.g.,

```
#- tf_models/research/slim/BUILD
py_library(
    name = "dataset_utils",
    srcs = ["datasets/dataset_utils.py"],
    deps = [
        # "//tensorflow",
    ],
)
```

However, this cause an issue when, say, define a local repository in tensorflow_serving/workspace.bzl as the one defined for including tf_models/research/inception.

```
#- tensorflow_serving/workspace.bzl
def tf_serving_workspace():
  native.new_local_repository(
    name = "inception_model",
    path = "tf_models/research/inception",
    build_file = "tf_models/research/inception/inception/BUILD",
  )

  native.new_local_repository(
    name = "slim_model",
    path = "tf_models/research/slim",
    build_file = "tf_models/research/slim/BUILD",
  )

  tf_workspace(path_prefix = "", tf_repo_name = "org_tensorflow")
```
The issue is that later bazel is complaining about cannot find @slim_model//tensorflow.

I have limit knowledge on bazel. From my understanding is that, a deps = ["//tensorflow", ] will look for a tensorflow directory under tf_models/research/slim. But there is no such directory as tf_models/research/slim/tensorflow.

I solved the issue by commenting out all deps on //tensorflow. Here is a detailed description of how I served slim-inception-v4 [https://gyang274.github.io/docker-tensorflow-serving-slim/0x02.slim.html](https://gyang274.github.io/docker-tensorflow-serving-slim/0x02.slim.html).

Would you kindly let me know the reason of including an explicit dependency to //tensorflow? Specifically,

1. What is the reason for adding this dependency recently?

2. Why //tensorflow, rather than define a http/git repository? And, how slim would know where //tensorflow is pointed?

3. How is this BUILD file expected to be used?

Thank you very much!

**Comment by kirilg** [comment]
I don't think that dependency is needed and could probably be safely removed. My guess is it's intended to link in a locally installed TensorFlow rather than code in the workspace (as you would do if it was a local folder or git_repository).

If you're up to it, perhaps try sending a PR to tensorflow/models removing those lines and if tests pass and the code gets merged, you can just use it as is.

**Comment by gyang274** [comment]
@kirilg, thank you for your explanation. I tried comment out these deps, and then referred to slim models from tensorflow_serving/example successfully.

Would you kindly give more details on how `//tensorflow` could refer to a locally installed TensorFlow, e.g., at which location, this local tensorflow is expected to be installed? If this is too complicate, would you kindly give a link to related documentation?

I would like to understand their purpose before sending a PR.

Thank you very much.

**Comment by kirilg** [comment]
On second thought, I don't think that's what it's for. I believe it's simply a bug and that dep should not be there. Just tried cloning that repo and it fails to build.

I'll close this bug since what you're doing is correct and it seems to be working after the fix to tensorflow/models, and will comment on that other issue you opened.

**Comment by gyang274** [comment]
Thank you, @kirilg. I will send a PR.

**Comment by gnedivad** [comment]
I'm curious how this solves your problem since everything in the slim module needs to import tensorflow.
