### ISSUE TITLE
How to build a client so used by external project?

### ISSUE THREAD

**Issue by kitterive** [tensorflow/serving#645]
I want to modify inception_client.cc as a library, which used by external project use common makefile,
But I found bazel build library  did not build all dependencies into the library. 
  how to do it?

**Comment by kirilg** [comment]
inception_client.cc is a binary with a main() so the BUILD file declares it as a [cc_binary](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/example/BUILD#L80). You can have your own version of the client that doesn't have that main() (so you'll use the ServingClient class as a library) and define a cc_library build rule instead, then you'll be able to link it as a library.

We don't use makefile in this repo, so I'm guessing that in order to include it in your repo that uses a makefile, you'd have to to fork it and use what's in TF Serving as an example.
