### ISSUE TITLE
Performance issue on CPU in comparison with Tensorflow model inference

### ISSUE THREAD

**Issue by BogdanRuzh** [tensorflow/serving#670]
I observe performance issue for CPU with Tensorflow model server. It doubles the time for inference in comparison to raw Tensorflow model inference. Both built with MKL for CPU only.

**Tensorflow MKL build:**
`bazel build --config=mkl -c opt --copt=-msse4.1 --copt=-msse4.2 --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-O3 //tensorflow/tools/pip_package:build_pip_package`

**Tensorflow server MKL build:**
`bazel build --config=mkl --config=opt --copt=-msse4.1 --copt=-msse4.2 --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-O3 tensorflow_serving/model_servers:tensorflow_model_server`

The target model is simple CNN for segmentation.

Raw Tensorflow model process an image in 0.17s.
Tensorflow model server process the same image in 0.32s.

How can I improve this performance? It's very critical for my application.

**Comment by BogdanRuzh** [comment]
Code to reproduce
https://github.com/BogdanRuzh/tf_model_service_benchmark

**Comment by chrisolston** [comment]
Hmmm. We haven't had this issue ourselves since the inference code path of TF-Serving is a pretty thin layer on top of TF. Of course there could be bottlenecks depending on the exact model and workload, e.g. if it's a very cheap model or the workload is generating excessive thread contention (either in the tensorflow Session threads or the gRPC rpc handler threads).

Please consider:
 1. Be sure the TF-Serving and TF binaries you are running are using the *same version of TF* under the hood.
 2. Be sure the tensorflow::Session config is identical in the two cases. In particular, the intra- and inter-op thread configuration is a really important factor in performance.
 3. Turn off TF-Serving batching. (This could help or hurt performance, depending on the case, but for apples-to-apples with raw TF you should disable it.)
 4. (Once you are sure it's apples-to-apples.) Run a CPU profile of TF-Serving to find out where the time is going.

**Comment by weberxie** [comment]
I met a problem similar to this one, https://github.com/grpc/grpc-java/issues/1758 mentioned it because of the gRPC warm up.
You can test multiple times in succession of one serving client.

**Comment by BogdanRuzh** [comment]
I've found a problem with performance in serialization step for big decoded images. It can be partially solved if transfer encoded images and decode them before feeding to the model.
@chrisolston maybe there is another way to reduce the time for serialization/deserialization steps?

**Comment by BogdanRuzh** [comment]
@weberxie that is well known grpc behavior. I measure performance for second and next steps only.

**Comment by Zhiqiang-Ye** [comment]
@chrisolston  how to run a cpu profile of TF-Serving？Using TensorFlow Profiler?

**Comment by yjhjstz** [comment]
>  In particular, the intra- and inter-op thread configuration is a really important factor in performance.

@chrisolston can you tell tensorflow::Session config more specific ?

**Comment by gautamvasudevan** [comment]
Closing due to staleness.

**Comment by vikotse** [comment]
> @chrisolston how to run a cpu profile of TF-Serving？Using TensorFlow Profiler?

Did you find the solution? I have the same question.
