### ISSUE TITLE
Error while building tensorflow serving docker container with Dockerfile.devel-gpu

### ISSUE THREAD

**Issue by siddharthm83** [tensorflow/serving#691]
I am unable to build the container using the below:
`docker build --pull -t tensorflow-serving-devel-gpu -f Dockerfile.devel-gpu .`
System info: Ubuntu 14.04 , Titan X GPU, Nvidia driver 375.26

Copying log file
[bazel-build.log](https://github.com/tensorflow/serving/files/1557811/bazel-build.log)

Searched for solutions, a few blogs have run into the same problem. For e.g.: 
https://blog.deeppoint.ai/deployment-keras-model-into-tensorflow-serving-with-gpu-e3137b8c8bfb
https://towardsdatascience.com/how-to-deploy-machine-learning-models-with-tensorflow-part-2-containerize-it-db0ad7ca35a7

Is there a suggested way forward?

**Comment by ChrisS2812** [comment]
I think the problem lies in the Tensorflow submodule. There was an error in the file 'numeric_types.h' which was fixed six days ago but the submodule in Tensorflow Serving was not yet updated. So this error is still present here.
See this Pull Request in the Tensorflow repository for reference: https://github.com/tensorflow/tensorflow/pull/15189.

@kirilg could you please look into this and update the Tensorflow submodule?

Thanks in advance!

**Comment by siddharthm83** [comment]
Thanks for the response, I used the TF1.4 branch and I was able to build the container.
