### ISSUE TITLE
Migrate inception_client from grpc beta to grpc

### ISSUE THREAD

**Issue by Michael-Jing** [tensorflow/serving#708]
I need to increase the max_message_length parameter which seems impossible in grpc beta, So I am asking could an serving client based on the non-beta version of grpc be provided.

**Comment by harshini-gadige** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow-servinig) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!

**Comment by gautamvasudevan** [comment]
This has been done with [resnet_client_grpc.py](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/example/resnet_client_grpc.py)
