### ISSUE TITLE
Using TensorFlow serving for local deployment of TensorFlow Model

### ISSUE THREAD

**Issue by soumya-ranjan-sahoo** [tensorflow/serving#785]
Hi Team,

I was trying to follow the tutorial at https://www.tensorflow.org/serving/serving_basic.

I am all good until I ran this command - bazel-bin/tensorflow_serving/example/mnist_client --num_tests=1000 --server=localhost:9000 (For testing the server using a built-in client utility). 
It returned me the following error : 

ImportError: dlopen(/Users/soumya.ranjan.sahoo/serving/bazel-bin/tensorflow_serving/example/mnist_client.runfiles/org_tensorflow/tensorflow/python/_pywrap_tensorflow_internal.so, 10): Symbol not found: _PyCObject_Type
  Referenced from: /Users/soumya.ranjan.sahoo/serving/bazel-bin/tensorflow_serving/example/mnist_client.runfiles/org_tensorflow/tensorflow/python/_pywrap_tensorflow_internal.so
  Expected in: flat namespace
 in /Users/soumya.ranjan.sahoo/serving/bazel-bin/tensorflow_serving/example/mnist_client.runfiles/org_tensorflow/tensorflow/python/_pywrap_tensorflow_internal.so

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

A quick help on this is highly appreciable. 

Thanks in advance.

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
