### ISSUE TITLE
Centos

### ISSUE THREAD

**Issue by AdamMiltonBarker** [tensorflow/serving#81]
Hi guys can anyone provide docs for installing on Centos, also would this be the preferable set up to use with SyntaxNet and be able to query it via an API? TIA

**Comment by kirilg** [comment]
Re:Centos - While we don't explicitly test on Centos, we did hear from users that got it to work. I believe our regular [install instructions](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/setup.md) should work for Centos as well, but please confirm by following the instructions and reporting any issues you encounter. One thing to note as was mentioned in https://github.com/tensorflow/serving/issues/6 is that some dependency packages are named differently in Centos (e.g. instead of zlib1g-dev, you'd want to use zlib-devel).

If that doesn't work, you can also try running it in a Docker container which should be supported on all platforms.

Yes, this setup is the correct one to use. You'll just need to export the SyntaxNet model and the serving component will be the same. In your server, you'll define the frontend and thus the API. See the inception example to see how that can be done.
