### ISSUE TITLE
how to serve pytorch or sklearn models using tensorflow serving

### ISSUE THREAD

**Issue by sujit420** [tensorflow/serving#835]
I have found tutorials and posts which only says to serve tensorflow models using tensor serving. In model.conf file, there is a parameter model_platform in which tensorflow or any other platform can be mentioned. But how, do we export other platform models in tensorflow way so that it can be loaded by tensorflow serving.

**Comment by chrisolston** [comment]
TensorFlow Serving is extensible such that one could write plug-ins for other types of models (i.e. not TensorFlow). Currently it would only work if the other type of model could be packaged or wrapped as a tensorflow::Session, because the RPC handlers assume they get Session objects. But to date we don't have any other plug-ins.

Out of the box, only TensorFlow is supported.

**Comment by ymodak** [comment]
Closing this issue since this comment explains the behavior of TensorFlow Serving extensions.

> TensorFlow Serving is extensible such that one could write plug-ins for other types of models (i.e. not TensorFlow). Currently it would only work if the other type of model could be packaged or wrapped as a tensorflow::Session, because the RPC handlers assume they get Session objects. But to date we don't have any other plug-ins.
> 
> Out of the box, only TensorFlow is supported.
