### ISSUE TITLE
Tensorflow Serving qps is too low，how can i improve it？

### ISSUE THREAD

**Issue by dailyncepu** [tensorflow/serving#842]
the qps of tf-server is low that my net-struct is mlp[512/256/128]，how can i improve it？

**Comment by qujinqiang** [comment]
i have the same  question

**Comment by walton-wang929** [comment]
same question

**Comment by walton-wang929** [comment]
wait for more people join. 

my vgg16 model. 
GPU CPU utilization is nearly full. but qps is just 7.

**Comment by yjhjstz** [comment]
@walton-wang929 have you tried batching request ?

**Comment by qujinqiang** [comment]
@yjhjstz  i hava try batching request, but the QPS is low

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
