### ISSUE TITLE
Problems on using preprocess codes between client and server.

### ISSUE THREAD

**Issue by Li-Shu14** [tensorflow/serving#858]
I want to `pre-process` the data sent by a `asynchronous client` before these data entering the model served by `tensorflow_model_server`.

 These `pre-process codes` are too complex to be implemented by  `tensorflow built-in functions` so it's almost impossible to make the  pre-processing a part of the `graph`.

 I also consider doing this on the `client` side, but the data after `pre-processing` will become 10 times larger ,which will greatly reduce the `transmission efficiency` between client and server. 

Is there any walk-arounds? I have finished asynchronous part using ways like  `mnist_client.py` and the pre-process part in `inception_saved_model.py` cannot help me with this problem.

 I really need as large `throughput` as possible.

**Comment by daikankan** [comment]
I meet the same problem with medical images, my preprocess include interpolate (with SimpleITK), padding, split with overlap (numpy), then request for each pieces。　Now I have to do this preprocess on client side, and the total size for transform is 10 times bigger.

**Comment by harshini-gadige** [comment]
@netfs  - Hi, could you please look into this issue ?

**Comment by hgadig** [comment]
Not sure if you got a chance to use Tensorflow Transform, which produces a preprocessing graph which you can use at training time, as well as include as a part of the serving graph (export) in order to avoid training-serving skew. 
Please take a look at [this](https://ai.googleblog.com/2017/02/preprocessing-for-machine-learning-with.html) which gives more information on this.

**Comment by hgadig** [comment]
Closing this issue as it is in "awaiting response" status for more than a week. Feel free to add your comments and we will reopen.
