### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: ./coref_kernels.so: undefined symbol: 

### ISSUE THREAD

**Issue by wncheng** [tensorflow/serving#880]
I got an error when running **kentonl/e2e-coref (https://github.com/kentonl/e2e-coref),** singleton.py

Traceback (most recent call last):
  File "singleton.py", line 13, in <module>
    import coref_model as cm
  File "/mnt/f/e2e-coref-master-02/coref_model.py", line 11, in <module>
    import coref_ops
  File "/mnt/f/e2e-coref-master-02/coref_ops.py", line 5, in <module>
    coref_op_library = tf.load_op_library("./coref_kernels.so")
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/load_library.py", line 64, in load_op_library
    None, None, error_msg, error_code)
tensorflow.python.framework.errors_impl.NotFoundError: ./coref_kernels.so: undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringB5cxx11Ev

**Comment by mcjoshi** [comment]
I am getting the same error. @wncheng Please let me know if you fixed this anyhow

**Comment by ymodak** [comment]
This question is better asked on [kentonl repo](https://github.com/kentonl/e2e-coref/issues) since it is not a bug or feature request for TensorFlow and it does not belong to official TensorFlow repo.
If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
